### ISSUE TITLE
FPS DROP 

### ISSUE THREAD

**Issue by UKboy4** [ValveSoftware/Dota2-Gameplay#15507] opened 2024-02-17 15:49 UTC
### Description

Hi! The other day I encountered a strange problem related to FPS in Dota. Recently, I bought myself a new RTX4060ti video card instead of a gtx1070ti. This led to a significant drop in FPS in the game dota 2
drops to 90 fps
All drivers have been reinstalled. Power supply costs maximum. Vertical sync is disabled.
spec: 
i5  13400 
rtx 4060ti
ram 32gb 3200

**Comment by IgorHoruzha** [comment] 2024-03-21 17:25
Do You still have the issue?

**Comment by UKboy4** [comment] 2024-03-24 01:01
ofc
I think the problem is because Dota does not use the processor to its fullest

**Comment by IgorHoruzha** [comment] 2024-03-24 15:59
#15942 Possible the same issue.

 Dota does not use the processor to its fullest in My PC also, the same is to Video  Card. But I have ~240FPS. 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/29505510/78c391e4-9e7c-4242-bb5c-e8d1ec3ece01)

Could You try to turn off Hyperthreading, and Virtualization in BIOS and check again, please?
Could You try to turn off Efficiency cores in BIOS and check again, please?
Could You check the video card temperature and load in the task manager when in happened, please? 
Are You able to check with gtx1070ti?

**Comment by IgorHoruzha** [comment] 2024-03-24 16:05
Could You try to Turn off  RAM AI boost, **AI Overclock Turner** in BIOS, please?
#11958 @StingyJack told that this helped him  versus FPS drops.

**Comment by IgorHoruzha** [comment] 2024-03-25 08:54
Could You try [this solution](https://www.reddit.com/r/DotA2/comments/11o9y3o/comment/jcdsib5/?utm_source=share&utm_medium=web2x&context=3)?

**Comment by UKboy4** [comment] 2024-03-25 17:40
![photo_5192662701665539639_w](https://github.com/ValveSoftware/Dota2-Gameplay/assets/160338262/f09a1800-1165-4114-bac5-77b2a09aca9f)
Thanks to your points, I was able to get a minimum FPS of 150 in fights. But still, I think that this is too strong a drop for such a system.

**Comment by UKboy4** [comment] 2024-03-25 17:40
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/160338262/1b45f26f-b0f4-4f1c-ae56-ae3246b2a8d0)
this is my settings

**Comment by UKboy4** [comment] 2024-03-25 17:41
my GPU is new btw. So can't be hot))

**Comment by UKboy4** [comment] 2024-03-25 17:49
Simply by logic, having 10 cores and 16 threads, Dota should work at high settings of at least 200 fps in fights.

**Comment by IgorHoruzha** [comment] 2024-03-25 17:55
I recommend to turn off all power settings in BIOS. It may significant improve the PC performance. 
**Try turn on Efficiency cores.** 

The best case use if You use [GPT Chat](https://chat.openai.com/gpts),  and check what **Each function** in BIOS do. And configure them on Your preference. For example to get the best performance.

I made so a while ago, and My PC started work significant faster. 
It seems by default Windows and Motherboard are set balanced to save power.  Be careful of electricity billing).

**Comment by IgorHoruzha** [comment] 2024-03-25 18:01
> Simply by logic, having 10 cores and 16 threads, Dota should work at high settings of at least 200 fps in fights.

Having 6 physical cores can be more beneficial than 12 logical cores if the application is unable to utilize all of them effectively. In scenarios where an application can only support 6 cores, having 12 logical cores might result in only half of them being utilized. Therefore, the application might only employ 3 physical cores(but 6 logical) as opposed to 6. This presents a feasible theory for such scenarios.

**Comment by IgorHoruzha** [comment] 2024-03-25 18:10
Also I recommend to turn off "Adjacent Cashe Line Prefetch" In some scenarios, it load processor cashe with  useless data. 

Updating BIOS may also improve  performance. But it reset all set settings to default, so is necessary to set them again. 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/29505510/fca5b3f2-8183-428f-9674-70de18815cd7)

**Comment by IgorHoruzha** [comment] 2024-03-25 18:21
Also there are some Windows settings that may significantly decrease  performance. For example  Microsoft Defender Real Time protection. A question Performance vs Security.  Turning off it significantly improve performants but make the PC less Security.

**Comment by IgorHoruzha** [comment] 2024-03-25 18:24
@UKboy4 I'm unsure whether to continue creating a guide on PC BIOS and Windows optimization. Would You prefer to use GPT Chat and YouTube to optimize Your PC for the best performance?

**Comment by IgorHoruzha** [comment] 2024-03-25 18:36
> ![photo_5192662701665539639_w](https://private-user-images.githubusercontent.com/160338262/316598314-f09a1800-1165-4114-bac5-77b2a09aca9f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTE1NDcsIm5iZiI6MTcxMTM5MTI0NywicGF0aCI6Ii8xNjAzMzgyNjIvMzE2NTk4MzE0LWYwOWExODAwLTExNjUtNDExNC1iYWM1LTc3YjJhMDlhY2E5Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQxODI3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjBjNDQxOGFmODUwMDMxYTQwZGQ4ZjQzM2Y1NmZlNjVkNGVmYTVkZjYyYzE2M2YxOTFlZTg1M2FiYTc4NTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zfzRA_Cyib5_uQVxdSgeq03NftknGCEBLUpApEtiV4U) Thanks to your points, I was able to get a minimum FPS of 150 in fights. But still, I think that this is too strong a drop for such a system.

Try turn on (E-Cores)Efficiency cores may improve the situation.  Your processor faced full load.  So 150 FPS due to it can't load fully the Video card. You can try to turn on not all but only 2 or 3 and check processor load again.

**Comment by IgorHoruzha** [comment] 2024-03-25 18:53
Also, when the problem is resolved, please close the issue.

**Comment by IgorHoruzha** [comment] 2024-03-25 19:23
> Also, when the problem is resolved, please close the issue.

It doesn't mean that I went away).

**Comment by UKboy4** [comment] 2024-03-26 05:05
now the processor frequency in load is 3.8
Although it should be 4.6

**Comment by IgorHoruzha** [comment] 2024-03-26 08:44
There are several BIOS settings that could influence a processor's frequency, such as those related to processor boosting and power-saving features. It means that if processor do not need 4.6 GHz, it won't take so, if power saving settings are turned on. 


Could You provide  the way You made the load?
Could You provide the frequency in stress test load, for example using [CPU-Z](https://en.wikipedia.org/wiki/CPU-Z)?
Important Make sure that Your processor colling system is able to  manage [148 W](https://ark.intel.com/content/www/us/en/ark/products/230495/intel-core-i5-13400-processor-20m-cache-up-to-4-60-ghz.html).

How many E-Cores are turned on now?
Could You provide Your Motherboard name, please?
**Could You provide Your lowest in game FPS now, please?**

Would You like to try to configure Your BIOS to have maximum performance? 
If so, could You provide a screenshot  of the Easy Mode and Advanced BIOS pages, please?
Could You try to change mode from normal to any upper(the name could be different It may name 'Game Try it',  or Turbo, or Maximum performance) in Easy Mode page, please?
If it will not help, we  could configure BIOS step by step using Advanced BIOS pages.

Could You provide Your RAM name? Is it DDR4 or DDR5?

**Comment by IgorHoruzha** [comment] 2024-03-26 09:14
Also it make sense to turn off all the E-Cores, but turn on Hyper Threading. And check the FPS, and the frequency.
IMO, there is more than one potential reason, so it may be a good Idea to make some experiments, to configure PC the best for Your needs.

**Comment by IgorHoruzha** [comment] 2024-03-30 05:59
@UKboy4  Is Your issue still actual?

**Comment by IgorHoruzha** [comment] 2024-04-01 15:07
@UKboy4  
I have one more option, could You try console command, please?
fps_max 500

**Comment by UKboy4** [comment] 2024-04-06 15:15
![Dota 2FpsChart061538](https://github.com/ValveSoftware/Dota2-Gameplay/assets/160338262/6ea6c3be-5f38-4373-a44b-414ad168674e)
What can u say about this??!)!!)!!
why i bought this pc

**Comment by UKboy4** [comment] 2024-04-06 15:16
130 fps avg is minimum pres

**Comment by IgorHoruzha** [comment] 2024-04-06 16:09
@UKboy4 Interesting. It looks like a nice tool to discover the impact of our experiments. What were Your PS BIOS settings during the test?

I also discovered some other tests on YouTube and got quite close results.
[GTX 1650 SUPER -- i5-13500 medium settings ~170-200fps](https://www.youtube.com/watch?v=y28kyoH8_zc)

[RTX 4060 Ti + i5 13400F Maximum Settings AVG 223 fps](https://www.youtube.com/watch?v=-FrA8PqVgJ0)

It looks like the game couldn't fully utilize the CPU and GPU to show the maximum top FPS count on some settings. I think something is also missing on our side. So, in my opinion, we can try to achieve an average of 200fps by changing settings. Would You like to continue playing with setting to find out the best FPS amount?

 
Could You also try this setting?
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/29505510/28bf5bf5-6e97-4293-82da-56baeff959a6)


[Found one more possible fix](https://www.youtube.com/watch?v=G5QgO3WPJaI).

**Comment by IgorHoruzha** [comment] 2024-04-06 16:27
Also do You use retracing technology?

**Comment by UKboy4** [comment] 2024-04-06 16:53
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/160338262/c2fb0a41-1533-4031-a3a1-1ae55b757473)
retracing technology - no

**Comment by UKboy4** [comment] 2024-04-06 16:55
so, u want to say this think, if i turn on DSR factors and make my res better it can help? Sounds interesting, i'll try it

**Comment by UKboy4** [comment] 2024-04-06 17:03
picture looks shitty

**Comment by UKboy4** [comment] 2024-04-06 17:04
it's working! That's  crazy. But picture looks bad((

**Comment by UKboy4** [comment] 2024-04-06 17:08
> Also do You use the [retracing technology](https://www.nvidia.com/en-us/geforce/news/gfecnt/20211/geforce-rtx-3060/#:~:text=The%20GeForce%20RTX%203060%20has,in%20over%2040%20RTX%20games.)?

how can switch off?

**Comment by IgorHoruzha** [comment] 2024-04-07 11:08
> it's working! That's crazy. But picture looks bad((

Let's try to get the best picture with playable  240FPS. Would You like to continue?
How many FPS do You have now?
Is Hyper-Threading on?
Are Efficiency cores on?
Is the Virtualization Disabled in BIOS?

Try to turn on also Compute Shaders.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/29505510/f08d39d5-ffef-4ae0-a6eb-3bedc6408387)


I see 2 ways of increasing the amount of fps. 
1) Increasing PC performance,  by  enabling turbo  frequencies and  maybe even overclocking. Turning off all inappropriate and energy saving settings in BIOS. The same is to Windows power plan settings.
2) Playing with picture quality and FPS amount. In Game settings, and Nvidia GeForce Driver settings.  It may sense to check each setting and it's impact on FPS and Picture quality. 

Which would You like to continue with?

**Comment by IgorHoruzha** [comment] 2024-04-07 11:14
> > Also do You use the [retracing technology](https://www.nvidia.com/en-us/geforce/news/gfecnt/20211/geforce-rtx-3060/#:~:text=The%20GeForce%20RTX%203060%20has,in%20over%2040%20RTX%20games.)?
> 
> how can switch off?

It appears to be My mistake; it seems that this setting is not available in the Nvidia GeForce driver settings, and Dota 2 does not support ray tracing.

**Comment by IgorHoruzha** [comment] 2024-04-07 11:22
> ![image](https://private-user-images.githubusercontent.com/160338262/320220660-c2fb0a41-1533-4031-a3a1-1ae55b757473.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODkxMjQsIm5iZiI6MTcxMjQ4ODgyNCwicGF0aCI6Ii8xNjAzMzgyNjIvMzIwMjIwNjYwLWMyZmIwYTQxLTE1MzMtNDAzMS1hM2ExLTFhZTU1Yjc1NzQ3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QxMTIwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjYwMmZhMzk3NGFhODRjMTJmYjMxNGRlOTBiOGI1NTZjMDIxZjAwZDhhNmI1MDBlZmE5ZTVjNmZlNDIzZTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s5nmjV1XdmuKsKdiLbNoB8n4OQYyg7oX-2_Q5E6-EW8) retracing technology - no

Try to turn on also Anti-Aliasing. And check the picture quality.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/29505510/746948d4-6c33-455d-a316-3e16a7044f7b)

**Comment by IgorHoruzha** [comment] 2024-04-07 11:34
> ![image](https://private-user-images.githubusercontent.com/160338262/320220660-c2fb0a41-1533-4031-a3a1-1ae55b757473.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODkxMjQsIm5iZiI6MTcxMjQ4ODgyNCwicGF0aCI6Ii8xNjAzMzgyNjIvMzIwMjIwNjYwLWMyZmIwYTQxLTE1MzMtNDAzMS1hM2ExLTFhZTU1Yjc1NzQ3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QxMTIwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjYwMmZhMzk3NGFhODRjMTJmYjMxNGRlOTBiOGI1NTZjMDIxZjAwZDhhNmI1MDBlZmE5ZTVjNmZlNDIzZTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s5nmjV1XdmuKsKdiLbNoB8n4OQYyg7oX-2_Q5E6-EW8) retracing technology - no

I also recommend to use console command:
fps_max 500

Or set FPS at least to 240.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/29505510/15912469-b290-4a76-b2ab-c3ddc66432d9)

**Comment by UKboy4** [comment] 2024-04-07 18:46
ur advice is  not helping. just let's end this

**Closed** 2024-04-07 18:46 UTC

**Comment by IgorHoruzha** [comment] 2024-04-08 14:18
> ur advice is not helping. just let's end this
@UKboy4  I'm sorry.  Is up to You.
