### ISSUE TITLE
Full sets can't be recognized in the Armory 

### ISSUE THREAD

**Issue by PandaGenius89** [ValveSoftware/Dota2-Gameplay#12282] opened 2023-09-28 16:43 UTC
### Cosmetic Item Name

A few full sets

### Description

A few full sets can't be recognized in the Armory

Enchantress: Song of the Solstice
Weaver: Dimension Ripper
Viper: King of the Corrupted Nest
Winter Wyvern: Aurora's Pyre
Faceless Void: Augur of Oblivion
Pugna: Furious Nethergeist
Shadow Fiend: Murder of Souls
Treant Protector: Haven of the Hinterheart
Disruptor: Upland Pride -
Axe: Carnage of the Endless Hunt
Ogre Magi: Stonebreak Excavators
Nyx: Sapphire Crab
Puck: Luminous Scarab
Tusk: Eternal Icebreaker
Pudge: Doll of the Dead

Upon these sets can't be recognized in the Armory.

I reported this problem before.(https://github.com/ValveSoftware/Dota2-Gameplay/issues/11760)
It is said fixed and closed.

But I logged in.Those problems still exsit.
For example,Tusk: Eternal Icebreaker.
In Screenshot 2,it shows I don't own it.
But actually,I have full set.
In Screenshot 3,there is no option of equip set.
So those sets are still can't be recognized.

### Example Match ID

None

### Screenshots
![1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143984926/744ed768-ca50-4faa-bcd2-dbf97b0b7ed7)
![2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143984926/6dff2a31-cbe2-45f1-846b-df4e3cc8d4ef)
![3](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143984926/9689ce27-75fd-446c-b2bb-093fc0c7624c)

_No response_

**Comment by vivi-lili** [comment] 2023-09-28 19:37
Sorry about that! I thought the original ticket meant that theses full sets were not shown in the Armory.

**Comment by vivi-lili** [comment] 2023-09-28 19:50
Unfortunately I'm not able to reproduce this issue.  Could you provide more specifics on the items you own for the full set, or a steam id to troubleshoot?

**Comment by PandaGenius89** [comment] 2023-09-29 02:59
> Unfortunately I'm not able to reproduce this issue. Could you provide more specifics on the items you own for the full set, or a steam id to troubleshoot?

my steam id 149102136
 
From Screenshot 1 to 6.
It shows I own the full set of Tusk: Eternal Icebreaker.But it can't be recognized in the system.
The problems exsit in the other sets that I shown in the article.

![1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143984926/cad6c932-6652-45f5-90b6-bdbec511ed0d)
![2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143984926/581fbe93-b785-42f0-94b4-2498995c460f)
![3](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143984926/d40691aa-b850-4d00-bdcb-0925982b823f)
![4](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143984926/04c1da48-cfb8-4ea1-b236-bb4f324a90c6)
![5](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143984926/b69c586f-4bd1-4d8d-b8c1-9a4cb4eed8eb)
![6](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143984926/502278f7-4b23-4c7d-8365-3669f9704665)

**Comment by PandaGenius89** [comment] 2023-09-29 03:04
> Unfortunately I'm not able to reproduce this issue. Could you provide more specifics on the items you own for the full set, or a steam id to troubleshoot?

For the set that can be recognized by the system,it will offer the option of equip set.(as I shown in below Screenshot )
But the sets I mentioned don't have the option.
So the sets are not recorded in the system.
And those sets are not shown either in purchasable or unavailable.
Actually those sets can be  purchased in the market.
![7](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143984926/38846058-10f2-41da-9833-bb686ace6ec5)

**Comment by vivi-lili** [comment] 2023-10-06 22:15
Found some issues with several of the sets you mentioned and they have been fixed in next patch.  Let me know if there are further problems.

**Comment by PandaGenius89** [comment] 2023-10-07 03:27
> Found some issues with several of the sets you mentioned and they have been fixed in next patch. Let me know if there are further problems.

It's fixed.Thank you.

**Closed** 2023-10-09 17:47 UTC
