### ISSUE TITLE
[Bug] Rubick's Telekinesis with aghanims shard crash the game

### ISSUE THREAD

**Issue by q7ice** [ValveSoftware/Dota2-Gameplay#3414] opened 2022-09-25 02:27 UTC
### Ability name

Telekinesis

### Description

1. Buy Aghanim's shard on the Rubick
2. Apply Telekinesis on the any unit
3. While this unit in flight click to the landing place
4. Game instantly crash

### Example Match ID (and possibly Timestamp)

6774917216 - 26:10

**Comment by Frelmed** [comment] 2022-09-25 02:45
yes i experienced this and still in the game

**Comment by Disctanger** [comment] 2022-09-25 03:27
The same issue just now happened.

**Comment by TheUnholyWrath** [comment] 2022-09-25 03:28
#3346 https://github.com/ValveSoftware/Dota2-Gameplay/blob/main/.github/HELP/HELP.md#before-submitting-a-report

**Comment by longdhnguyen** [comment] 2022-09-25 04:05
Experienced this issue. Ruined my game.

**Comment by dron1t** [comment] 2022-09-25 08:00
duplicate of: #3346

**Closed** 2022-10-04 19:36 UTC
