### ISSUE TITLE
Issue with player view on watch player live

### ISSUE THREAD

**Issue by kingcrimson43** [ValveSoftware/Dota2-Gameplay#583] opened 2022-06-05 06:06 UTC
### Description

For the past few months when i load in to watch a friends game the camera will set itself mid when attempting to watch from their perspective. It will eventually right itself but after tabbing through all the player views in the game or as another player suggested, moving the camera manually to the back of the dire fountain and having it reset on player view a few times. Seems to be a problem from the 0 to 10 game minute mark. Has become a daily issue when trying to watch other players gameplay in the client. Thanks

**Comment by Uwila** [comment] 2022-06-05 08:23
Duplicate of #5 , please close this issue.

**Comment by real-vaLor** [comment] 2022-06-05 15:01
This is a duplicate, the update fixing this comes on the 8th.

**Closed** 2023-11-14 06:17 UTC
