### ISSUE TITLE
mini map markers positioned wrong after 7.33

### ISSUE THREAD

**Issue by shakyatul** [ValveSoftware/Dota2-Gameplay#8218] opened 2023-04-21 17:46 UTC
<img width="251" alt="image" src="https://user-images.githubusercontent.com/91882145/233701308-34369c8c-9949-4910-bdfa-65badade7c2c.png">

The mini map icons and markers are positioned incorrectly, and the edges of the maps cannot be seen on the mini map. This is on a custom lobby, might be seen on normal matches too. Also tried it with defualt and other HUDs, same issue. 

Pretty unplayable bug, can't see where things are in the mini map and the roshan put is out of the map area.

**Comment by EugeneOak** [comment] 2023-04-21 18:34
Having the same issue, not sure how to fix it.

**Comment by webstek** [comment] 2023-04-21 19:44
Also having this issue. I'm on windows 10, but my friend on windows 11 isn't having it.

**Comment by shakyatul** [comment] 2023-04-21 22:45
I'm on Windows 11 though and still getting the issue

**Comment by MAL1S** [comment] 2023-04-23 03:15
Having this issue too

**Comment by aldrenean** [comment] 2023-04-23 06:45
Having the same problem -- the icons for all heroes, towers, and creeps seem to be slightly zoomed out of alignment with both the map and the fog of war display. I tried toggling every mini-map related option and couldn't get it to fix itself. Also tried different HUDs.

**Comment by aldrenean** [comment] 2023-04-23 09:03
On further searching, I finally found someone blaming the Desert terrain, which does indeed seem to have been the cause. So really this is a bug with the terrain item -- I don't have any others to test with, but default does not have this issue.

Unequipping the Desert terrain item fixes the minimap problem.

**Comment by shakyatul** [comment] 2023-04-23 18:30
I tried a couple of terrains and it does seem to fix it. The only terrian that I found the issue in was the desert one, swapping it to the default or other few did seem to fix the issue

**Comment by nathank-valve** [comment] 2023-04-27 22:23
Fix should be live now. Closing

**Closed by nathank-valve** 2023-04-27 22:23 UTC
