### ISSUE TITLE
Dawn breaker loses Luminosity Stack when she attack misses

### ISSUE THREAD

**Issue by HarvestDubois** [ValveSoftware/Dota2-Gameplay#706] opened 2022-06-08 01:22 UTC
### Description

Upon missing an attack Dawn Breaker will lose her luminosity stack.
I have tested this along side Wraith king where Mortal strike does not go on cooldown upon missing the attack.
same for storm spirit not losing his overload charge upon missing the attack.

**Comment by Bu3nyy** [comment] 2022-06-08 06:37
Not necessarily a bug. This has to be viewed individually for each ability.

For example, Fury Swipes was intentionally changed to behave this way.

**Comment by BenjinZA** [comment] 2022-06-08 14:20
Easily reproducible with Windranger, since Windrun grants 100% evasion.

Once Dawnbreaker has 3 stacks of Luminosity, if she misses her next attack it will remove all charges without getting any benefit.

@Bu3nyy I'm not sure if Fury Swipes is equivalent, as the debuff does not get removed from the target if Ursa misses an attack. 

Maybe a better comparison would be Naga Siren or Slardar, as they both have passives that take a certain amount of hits to "charge". For both of these heroes, missing an attack when on 5 and 3 charges does not remove the counting buff.

Though I agree this could be intended behaviour, it does seem like a bug.

**Comment by Daar543** [comment] 2022-06-19 18:55
Does she get the stack while missing as well?

**Comment by Dota-Exp** [comment] 2022-12-21 07:21
This will be fixed in upcoming update. Thank you.

**Closed by Dota-Exp** 2022-12-21 07:21 UTC
