### ISSUE TITLE
If you change the hero, taunt disappears

### ISSUE THREAD

**Issue by kliklik1992** [ValveSoftware/Dota2-Gameplay#19112] opened 2024-06-04 19:39 UTC
### Cosmetic Item Name

taunts

### Description

If you change the hero, taunt disappears and saving the set doesn't help. I attach a video to demonstrate this.

### Example Match ID

123

### Screenshots

https://www.youtube.com/watch?v=iwK9tH_4Sik

**Comment by m0x1mqa** [comment] 2024-06-10 09:04
такая же фигня, нигде нет решения

**Comment by BgueC6595** [comment] 2024-06-17 13:01
duplicate of #18703

**Comment by chrisf-valve** [comment] 2024-06-18 15:54
This should be fixed in an update that shipped yesterday night.

**Closed by chrisf-valve** 2024-06-18 15:54 UTC
