### ISSUE TITLE
Monkey king's mischief spends reindrops

### ISSUE THREAD

**Issue by failking16** [ValveSoftware/Dota2-Gameplay#338] opened 2022-06-03 06:37 UTC
### Ability name

Mischief

### Description

when you are evading any spell with mischief and you have reindrop then u will not get any magick daamge deu to mischief, but reindrop's charge will be use

https://user-images.githubusercontent.com/66196978/171797599-fb723805-7dea-4c96-991f-40612f6d6648.mp4

d

### Example Match ID (and possibly Timestamp)

all replayes pendings and can't download

**Comment by coderfrom94** [comment] 2022-06-03 07:17
This should be marked as [Major]

**Comment by Daar543** [comment] 2022-06-03 16:01
Does not have to be a bug, depends in what order are the reductions calculated.

**Comment by failking16** [comment] 2022-06-03 16:19
the problem is that mischief evades any damage and reindrops should not be consumed

**Comment by OraCLesofFire** [comment] 2022-06-04 08:51
This is intended behavior. Raindrop has top priority for reduction when damage is taken. This means even if the damage itself is mitigated to 0 (via mischeif, backtrack, fates edict) the raindrop will reduce the damage before the mitigation occurs. This is consistent with how Pipe and other shields work (reducing damage before every source of mitigation except mana shield).

**Comment by Dota-Exp** [comment] 2022-09-21 01:53
Currently working as intended

**Closed by Dota-Exp** 2022-09-21 01:53 UTC
