### ISSUE TITLE
Rapier bug drop

### ISSUE THREAD

**Issue by Maksmirai** [ValveSoftware/Dota2-Gameplay#16037] opened 2024-03-23 00:43 UTC
### Item name

Divine Rapier

### Description

Now it will be difficult to understand what I'm trying to convey, but you try, If the hero who bought the rapier dies and the enemy takes it away, after which the enemy with the rapier dies and you take it away, after which you die again, and if an ally picks it up, the rapier becomes active and cannot be returned to the hero to whom it belongs
![bug2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/97899526/acf70e44-40b1-4542-a28c-9fef77f0c624)
![bug1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/97899526/2b0aa7c0-3597-456c-9ff9-ca2803aad537)

### Example Match ID and Timestamp

ex 7650116434 - 52

**Comment by commentator24** [comment] 2024-03-23 07:54
rapier has 2 states. 1st state enemy hasn't pick it up. Can drop rapier anytime you want. 
Ally heroes can pick it up for you then drop to ground or return to you anytime. When they hold it, it has no effect for them, stay passive / unusable.

the 2nd state is after enemy picked it up. Cannot drop rapier anymore. Stays locked.
by this time ally heroes who picked it up can use it. Stay active / usable when they hold it. And they cannot return it to you or drop to ground. The only way is if they die and it's dropped.

this is already explained in tooltip i think
you can close this issue not a bug

**Comment by Maksmirai** [comment] 2024-03-23 09:58
Look at the second picture, there Tuskar lost the rapier and the allied phantom took it away, after which it became active and in the first picture it is clear that she cannot lay out the object although it belongs to Tuskar

**Comment by commentator24** [comment] 2024-03-23 14:38
When Tuskar lost the rapier you let the enemy picked it up at least once. This makes the rapier becomes the 2nd state: ally heroes like PA can no longer drop rapier to ground / lay out the object although it belongs to Tuskar.

here is an example. Tuskar buys rapier, and luna is ally hero.

This is 1st state (enemy hasn't pick it up at all). item is muted. ally heroes cannot use. No effect. Luna can drop it to ground / return to Tuskar.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/9fa86f4c-a18f-43a0-b184-201a4af77e61)

This is 2nd state (after enemy picked up / stole rapier). item is now usable by allies. Luna cannot drop or return to Tuskar until death.
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/c21f13f4-ecf9-4753-a00a-be856a9c6ae8)
can use the active now. item is not muted
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/78f8a8c2-0f90-4f73-9134-2b03119aeaa9)

hope you understand my explanation.
you can close the issue this is not a bug.

**Comment by Maksmirai** [comment] 2024-03-23 15:16
Try to do this 
1. Buy yourself a rapier
2. To die with a rapier and give it to the enemy
3. Kill the enemy and take the rapier on your hero
4. Die your hero with a rapier 
5. pick up a rapier by an ally (isn't this the 1st condition that is mentioned in the description that it will not work for allies), but in this case, the rapier picked up by an ally will be active and it cannot be laid out.

Perhaps I do not fully understand how the 2nd state works and how it is related to the fact that the allied hero who picked up the rapier from me can use it.

**Comment by commentator24** [comment] 2024-03-23 17:40
1. Buy rapier = 1st state. This is the 1st condition where it it doesn't work for allies because enemy hasn't touch the rapier. You can give it to allies but they cannot use it. item is muted. they can give it back to you.
2. To die with a rapier and give it to the enemy = rapier is touched by enemy. Change rapier to 2nd state forever. Until game is over. Now allies who picked it up instead of you cannot give it back to you (they cannot drop it to the ground), but item is not muted, and they can use it. they get +350 dmg or 100 dmg if they prefer the +spell dmg.
3. Kill the enemy and take the rapier on your hero OR allies OR enemies = Enemy touched rapier. it becomes 2nd state forever. rapier ownership will keep changing to whoever picked it up.
4. Die your hero with a rapier = doesn't matter if you die, or ally die, or enemy die. still 2nd state.
5. pick up rapier by an ally = doesn't matter if ally picked it up after, or you picked it up after. still 2nd state. to stay 1st state it requires the rapier not to be touched by enemy at all.

**Closed** 2024-03-23 17:59 UTC
