### ISSUE TITLE
Taunts automatically become unequipped 

### ISSUE THREAD

**Issue by Kyleoth** [ValveSoftware/Dota2-Gameplay#19449] opened 2024-06-17 10:25 UTC
### Cosmetic Item Name

all Taunts

### Description

Taunts automatically become unequipped even when i equip them before game, when game starts, they are unequipped.

### Example Match ID

7769344906

**Comment by BgueC6595** [comment] 2024-06-17 13:01
duplicate of #18703

**Comment by chrisf-valve** [comment] 2024-06-18 15:55
This should be fixed in an update that shipped yesterday night.

**Closed by chrisf-valve** 2024-06-18 15:55 UTC
