### ISSUE TITLE
Game removed me because of the inactivity

### ISSUE THREAD

**Issue by akusu211** [ValveSoftware/Dota2-Gameplay#12384] opened 2023-10-01 02:46 UTC
### Description

While playing i go to highground in our base because they got the ageis so we wait in the highground and im not afk. Then it came that the system detects that im not in game so it removed me from the game and caused me abbandon.  its hard to accept because its a ranked game and i want the mmr can you fix this asap.

### Example Match ID (and possibly Timestamp)

7359660146 - 46:59

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/138882788/60d7d68f-185d-4223-b16d-f72248543af9)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/138882788/60520eb3-7618-4ccd-8b8f-0ddda7002465)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/138882788/bf92e156-02e6-4c93-a01c-5289accf2005)

**Comment by commentator24** [comment] 2023-10-01 07:40
#2084 no xp within 5 min = abandon penalty
using skills in base, heal allies etc does not matter.
unfortunate, but now you know. thats why griefers afk in trees near lanes so they still get xp but don't get abandon. 
this is not a bug. please close this issue

**Closed** 2023-10-01 07:46 UTC
