### ISSUE TITLE
Dawnbreaker (Starbreaker) Shard - Drow Ranger (Gust) Interaction

### ISSUE THREAD

**Issue by S1lv3r4ng3l** [ValveSoftware/Dota2-Gameplay#15972] opened 2024-03-17 00:43 UTC
### Ability name

Celestial Hammer (Shard)

### Description

Dawnbreaker Starbreaker (Shard) vs Drow Gust

Is this interaction normal ? 
=> The Gust Move back Dawnbreaker during Starbreaker bkb

https://streamable.com/79efq9

### Example Match ID (and possibly Timestamp)

7640899503 - 29:27

**Comment by commentator24** [comment] 2024-03-17 13:27
tested demo gust does not knockback during dawn's shard.
seems you can control the movements during starbreaker now (but not changing direction you're facing), so most likely you moved back yourself during shard 2nd or 3rd hit to run away. 
you can close this issue not a bug

**Comment by S1lv3r4ng3l** [comment] 2024-03-17 18:08
That's true, i didn't know that !

Sorry, thanks for reply

> tested demo gust does not knockback during dawn's shard. seems you can control the movements during starbreaker now (but not changing direction you're facing), so most likely you moved back yourself during shard 2nd or 3rd hit to run away. you can close this issue not a bug

**Closed** 2024-03-17 18:08 UTC
