### ISSUE TITLE
Dota2 crash after Summer 2023 update on linux

### ISSUE THREAD

**Issue by neimovirne** [ValveSoftware/Dota2-Gameplay#11023] opened 2023-08-30 22:11 UTC
### Description

When I try to change windowed/fullscreen option dota crashes EVERY TIME
Ubuntu 23.04 X/nvidia-535.86.05 driver
6.2.0-31-generic kernel
All system updated 

### Screenshots

https://github.com/ValveSoftware/Dota2-Gameplay/assets/2023595/3c831d80-f733-4c03-9cc3-5695da15a544

Here is crush dump file
[crash_20230830234855_2.txt](https://github.com/ValveSoftware/Dota2-Gameplay/files/12480941/crash_20230830234855_2.txt)

**Comment by Bodyash** [comment] 2023-08-30 22:32
https://github.com/ValveSoftware/Dota-2/issues/2433 - same for me, game crashing on start (it's already in fullscreen mode probably)

**Comment by SethDusek** [comment] 2023-08-30 22:41
Same issue here, it seems the root cause is alt-tabbing or anything that causes the game client to focus (for example I have overlay disabled, so steam notifications show up in the bottom right as windows, everytime one shows up it immediately crashes the game).

**Comment by Memoframe** [comment] 2023-08-30 22:42
Alt-tabbing, game accept button pop up closing client too.

**Comment by Bodyash** [comment] 2023-08-30 22:43
> Same issue here, it seems the root cause is alt-tabbing or anything that causes the game client to focus (for example I have overlay disabled, so steam notifications show up in the bottom right as windows, everytime one shows up it immediately crashes the game).

My client don't launch at all

**Comment by neimovirne** [comment] 2023-08-30 22:44
and also I got very weird effect after my death, screen become so white 
![Знімок екрана з 2023-08-31 01-38-30](https://github.com/ValveSoftware/Dota2-Gameplay/assets/2023595/b4d6f090-11b1-4eef-8bc6-318b041fa951)

**Comment by neimovirne** [comment] 2023-08-30 22:47
> This repo is gameplay related, not a client bugs I think.


well its a Valve problem cause its a first link while I google "dota2 bugreport" ))

**Comment by Memoframe** [comment] 2023-08-30 22:52
Just in case someone wonna try - switching Proton versions seems to have not effect, at least GE Proton 13 does not help.

**Comment by Bodyash** [comment] 2023-08-30 22:54
> Just in case someone wonna try - switching Proton versions seems to have not effect, at least GE Proton 13 does not help.

Dota2 is native, proton is not used.

**Comment by Memoframe** [comment] 2023-08-30 22:58
> > Just in case someone wonna try - switching Proton versions seems to have not effect, at least GE Proton 13 does not help.
> 
> Dota2 is native, proton is not used.

Yeah my bad, it's been so long ago I even forgot about this lol.

**Comment by SethDusek** [comment] 2023-08-31 02:19
This issue seems to be fixed for me. Consider closing this if its also working for you

**Closed** 2023-08-31 02:33 UTC
