### ISSUE TITLE
Safty Bubble is Bug on Medusa 

### ISSUE THREAD

**Issue by dota2player01** [ValveSoftware/Dota2-Gameplay#14996] opened 2024-01-16 04:43 UTC
### Item name

Tier 1 Safety Bubble

### Description

hi
i cant tell you how much bugy is this item on medusa just watch and see!
1.This item alays stays on full barrier!
2.Beacuse its alwaya full barrier hes blink never gets muted after taking hit 
3. other thing is satanic not givinig lifesteal
4. and god know how many other bugs this item has on medusa....

fix it fast ty

### Example Match ID and Timestamp

7539704455 - 8:40min(bubble always full) -26min(dagger not muted) - 39min(satanic)

**Comment by Aluerie** [comment] 2024-01-16 08:46
there is no bugs in here.

* Dusa barier takes priority over all damage manipulation. Thus annoying blink interaction but not a bug. 
* lifesteal is vased of phys damage the target takes while dusa takes very small amount due to innate 98% barrier. Also intended. 

you can close the issue.

**Closed** 2024-01-17 00:29 UTC
