### ISSUE TITLE
Overwatch crashing while opening the game to review

### ISSUE THREAD

**Issue by juanqdt** [ValveSoftware/Dota2-Gameplay#8399] opened 2023-04-22 20:53 UTC
### Description

Being assigned an overwatch case. Download the repetition, click on review. Opening the review crashed on loading screen. m

### Screenshots

![image](https://user-images.githubusercontent.com/13675334/233806144-62ea3899-7cc8-4ba1-a064-978b9f581af9.png)

**Comment by pontuslaestadius** [comment] 2023-04-23 06:57
Duplicate of #8183 please close and upvote the existing ticket.

**Comment by Nathanael-Valve** [comment] 2023-05-22 22:59
Fixed

**Closed by Nathanael-Valve** 2023-05-22 22:59 UTC
