### ISSUE TITLE
Templar Assassin's Psionic Trap new autocast mode is not working as intended

### ISSUE THREAD

**Issue by IohanChristian** [ValveSoftware/Dota2-Gameplay#8053] opened 2023-04-21 03:23 UTC
### Ability name

Psionic Trap

### Description

Templar Assassin's Psionic Trap new autocast mode is not working as intended.
The traps are being activated in a random order, no matter where the cursor is.
The intended behaviour is activating the trap closest to the cursor location.

This is the video proof I recorded in demo mode - https://youtu.be/yzZ5b7hHQD8

### Example Match ID (and possibly Timestamp)

https://youtu.be/yzZ5b7hHQD8

**Comment by flovnes** [comment] 2023-04-21 22:07
When the trap ability is in the autocast state, it seems to detonate the lowest right one (relative to the map)
https://youtu.be/tCb1fGrZM20

**Comment by Aluerie** [comment] 2023-04-24 22:19
Fixed, you can close the issue.

**Comment by rosshadden** [comment] 2023-04-24 22:28
It is indeed fixed, thank you! It doesn't work with the minimap like her Aghanim's Scepter upgrade does unfortunately, but the game never claimed to so that's not a bug.

**Closed** 2023-04-25 21:19 UTC

**Comment by Aluerie** [comment] 2023-04-26 16:05
Opened #8675 for that request.
