### ISSUE TITLE
Hero Guide's aren't showing anything 

### ISSUE THREAD

**Issue by RotDrachen** [ValveSoftware/Dota2-Gameplay#13130] opened 2023-10-29 15:07 UTC
### Description

I was on a game and using Gyrocopter for the first time, when I wanted to view the guide of abilities and items for that hero it wasn`t showing anything, I tried to restart my Dota 2 client but the problem persisted. 

### Example Match ID (and possibly Timestamp)

7405705530

### Screenshots

![Captura](https://github.com/ValveSoftware/Dota2-Gameplay/assets/149315847/341ad764-989a-4268-b967-f03ef2b8410b)
![Captura 1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/149315847/679695f4-3a3a-4911-8435-b4ee594a2594)

**Comment by Sonuvaharris** [comment] 2023-11-09 10:49
This bug only appears for me in-game. Any guides I've viewed BEFORE a match started (including drafting phase) work correctly, but once the matchmaker has found a game, no new guides will load.

**Comment by RotDrachen** [comment] 2023-11-09 12:15
> This bug only appears for me in-game. Any guides I've viewed BEFORE a match started (including drafting phase) work correctly, but once the matchmaker has found a game, no new guides will load.



In my case it doesn’t matter, the guides don’t appear even having opened before the match started. It’s quite strange, and now having played for some time I realize it happens with many heroes.

**Comment by nivhty** [comment] 2023-11-11 13:19
I got the same issue, the build guide sometimes shows up and sometimes not in the demo hero section, if it doesn't show up, clicking the view guide (which opens another browser) will crash the game.

**Comment by zchilds** [comment] 2023-11-13 02:30
Having the same issue

**Comment by fortvile** [comment] 2023-11-14 04:06
very frustrating bug

**Comment by htmyname** [comment] 2023-11-14 10:14
Another bug occurs when you press the 'view' button, the game crashes

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33270133/22c50e12-2748-447c-ae8c-f194e1c4bb1a)

**Comment by ResendeAndrey** [comment] 2023-11-15 18:00
bad bug. The same with me

**Comment by patroclus1** [comment] 2023-11-18 21:18
Same issue here. 

The only workaround at this moment is to choose the guide before the match (pre-loading it). But in the match other guides will not load

**Comment by Fenivan** [comment] 2023-12-06 20:52
Same bug happening here for at least 2 months now, can valve pls fix this is unacceptable....

**Comment by StupydHors** [comment] 2023-12-07 19:53
Still an issue for me for the past 3+ months

**Comment by bptrsn** [comment] 2023-12-16 14:20
Not fixed with 7.35

**Comment by anthenorjr** [comment] 2023-12-19 22:30
Game breaking bug, Makes me lose a lot of games with new heroes I don't play a while after new patch. Please look into it:? Can''t be this hard.

**Comment by brumbrum05** [comment] 2023-12-20 19:38
Hi,

Same here. Whenever I open a new guide. A download is started under “dota 2 workshop item”. After restarting the game when the item is downloaded. It still does not appear. I tried validating game files, clearing cache, allowing downloads during gameplay. If there are any other suggestions I would like to hear. 

King regards

**Comment by mihaidraghici98** [comment] 2023-12-21 15:17
I have this issue too. Tried toggling downloads while playing, running as administrator, cleaning caches, pre-loading before matchmaking, fresh install (steam + dota2, including registries cleanup), but this was not fixed.

This is so awful and hugely impacts the gameplay. A persisting issue which doesn't seem to have even a way of debugging...

**Comment by dlabsnl** [comment] 2023-12-22 22:37
Try: https://www.reddit.com/r/DotA2/comments/18l1wm9/how_to_fix_ingame_guides_not_loading/

**Comment by neogamerdrew** [comment] 2023-12-23 08:20
The fix in the reddit link above did not work for me. I also don't seem to be able to load guides even if I select them during hero draft. PLEASE fix this! Very frustrating bug.

**Comment by D4n1aLLL** [comment] 2023-12-24 10:06
56 days and still not fixed

**Comment by brumbrum05** [comment] 2023-12-28 12:21
> Try: https://www.reddit.com/r/DotA2/comments/18l1wm9/how_to_fix_ingame_guides_not_loading/

have tried this aswell, did not work. Since the workshop items are downloading while in game. This does not seem like a logical solution.

**Comment by mitharas** [comment] 2023-12-28 12:26
Happens to me as well from time to time, rather annoying. +1 for visibility.

**Comment by phhoffmann** [comment] 2023-12-28 12:40
Happens here too

**Comment by kostakis** [comment] 2023-12-29 11:01
Can we finally fix this ?

**Comment by Korndaweizen** [comment] 2023-12-30 02:25
Bump

**Comment by thefoxdeveloper** [comment] 2023-12-30 22:16
still bugged jesus

**Comment by neogamerdrew** [comment] 2023-12-31 05:31
https://www.reddit.com/r/DotA2/comments/18swz83/dota_2_guides_wont_load_fix/

This fix worked for me

**Comment by brumbrum05** [comment] 2024-01-02 15:29
> https://www.reddit.com/r/DotA2/comments/18swz83/dota_2_guides_wont_load_fix/
> 
> This fix worked for me

did not work for me

**Comment by dominikkremer** [comment] 2024-01-03 14:19
I can confirm this issue. 

There is a solution yet to be found.

**Comment by neogamerdrew** [comment] 2024-01-09 05:09
> https://www.reddit.com/r/DotA2/comments/18swz83/dota_2_guides_wont_load_fix/
> 
> This fix worked for me

Turns out this fix did NOT work, it only seemed like it did temporarily in a bot match when I tested.

**Comment by kostakis** [comment] 2024-01-09 19:59
Can we finally fix this please

**Comment by MoaMission** [comment] 2024-01-20 00:55
I think it's obvious that this is an intentional bug left in by the devs. I can't fathom the purpose of not fixing guides being broken other than laziness: the players who develop the game aren't interested in new players or the shrinking base of normal players. This game is being managed for a selective group of high-mmr professionals who do nothing but smurf and buy accounts a their appropriate skill level.

It's similar to how console text chat was left open for a very long time after the behavior score update wasn't working properly.

**Comment by kostakis** [comment] 2024-01-20 08:37
For the love of god please fix this .....

**Comment by bptrsn** [comment] 2024-01-20 08:45
Today's update fixed guides for me.

**Comment by eugene-valve** [comment] 2024-01-22 17:44
Hi everyone, we recently shipped a fix that hopefully fixes guides not loading for some people. If you continue to run into issues, feel free to ping me or re-open this issue.

**Closed by eugene-valve** 2024-01-22 17:44 UTC

**Comment by brumbrum05** [comment] 2024-01-23 20:08
thank you.

**Comment by kostakis** [comment] 2024-01-23 20:21
Finally

**Comment by dominikkremer** [comment] 2024-01-24 18:53
Works! Thank you, very helpful.

**Comment by lesha1201** [comment] 2024-02-24 20:51
Played today and had this issue again.
