### ISSUE TITLE
zeus passive skill is not working

### ISSUE THREAD

**Issue by mynameisnyepp** [ValveSoftware/Dota2-Gameplay#9424] opened 2023-05-26 03:19 UTC
### Ability name

Lightning hands

### Description

zeus passive skill is not working

### Example Match ID (and possibly Timestamp)

7171282387 - 37:14

**Comment by TheUnholyWrath** [comment] 2023-05-26 03:50
Lightning Hands is an Auto-Cast ability. When you turn it off, Zeus' attacks won't create Arc Lightnings until you turn it back on. This is not a bug, please close this issue

**Closed** 2023-05-26 05:36 UTC
