### ISSUE TITLE
Treant Protector Ult with lvl 25 talent cannot root Juggernaut if Jugg uses Ult

### ISSUE THREAD

**Issue by ekgnom** [ValveSoftware/Dota2-Gameplay#5940] opened 2022-12-13 05:40 UTC
### Ability name

Overgrowth 

### Description

Treant Protector Ult, Overgrowth, with his lvl 25 talent "Overgrowth Undispellable", still can not root Juggernaut if Jugg uses Ult, which is kinda strange and kinda makes juggs ult overpower. As comparison, if rooted by Treant's ult, Tusk's snowball will not work. Please analyse if this is a bug or intended.

### Example Match ID (and possibly Timestamp)

00000

**Comment by TheZett** [comment] 2022-12-13 23:11
Omnislash can be casted while rooted, due to not being considered a proper mobility spell.

**Comment by Dota-Exp** [comment] 2022-12-22 02:35
Working as intended. Closing the issue.

**Closed by Dota-Exp** 2022-12-22 02:35 UTC
