### ISSUE TITLE
Bingo Token suddenly disappeared..

### ISSUE THREAD

**Issue by MrGuchii** [ValveSoftware/Dota2-Gameplay#21169] opened 2024-08-23 19:00 UTC
### Description

i have 21 bingo token that i haven't used after purchasing the level 50 compendium after claiming all the items.. i played a couple of games and reached level 51 on compendium and claimed another set of bingo tokens but suddenly all the previous bingo tokens i havent used vanished and i only have 3 bingo tokens that i just got form leveling 51 compendium.. i thought its just a minor glitch and tried to use the current 3 tokens on "upgrade square" thinking that the previous 21 will reappear but to my surprise it didn't..currently i have only 1 bingo token while i only used 2 out of 24 that i should currently have in total.. 

### Screenshots

<img width="1920" alt="bingo" src="https://github.com/user-attachments/assets/f32df2a8-7e04-4e87-811f-6f69ab0212d5">

**Comment by eugene-valve** [comment] 2024-08-24 03:43
Duplicate of #21171

**Closed by eugene-valve** 2024-08-24 03:43 UTC
