### ISSUE TITLE
Lotus orb reflects Dragon Tail twice.

### ISSUE THREAD

**Issue by misterysad** [ValveSoftware/Dota2-Gameplay#412] opened 2022-06-03 15:03 UTC
### Item name

Lotus Orb

### Description

**Lotus orb** is reflecting Dk **Dragon Tail** twice. (Damage and stun) 

**Counterspell** and **Mirror Shield** are working as intended

https://user-images.githubusercontent.com/106823187/171879938-8ddb7559-485f-4703-8911-2f79703f5c3c.mp4

.

### Example Match ID and Timestamp

Demonstration attached

**Comment by jeffercize** [comment] 2022-06-03 15:22
I dont think .mp4 video files are supported on github

**Comment by NMOTH** [comment] 2022-06-03 15:30
> I dont think .mp4 video files are supported on github

I can view the video he attached. Please check on chrome web version of github.

**Comment by JustDarker** [comment] 2022-06-03 18:02
It's not a bug, it's just how Lotus Orb works. Check it's tooltip, it doesn't block spells, only reflects it.

**Comment by ivanovitch2401** [comment] 2022-06-03 18:42
> It's not a bug, it's just how Lotus Orb works. Check it's tooltip, it doesn't block spells, only reflects it.

Yes, but DK is wearing a linken sphere. It should've just broken linken, not apply the stun + damage.

**Comment by BenjinZA** [comment] 2022-06-03 18:59
Combat log only shows one instance, but damage done is doubled when reflecting Dragon Tail.

![image](https://user-images.githubusercontent.com/43580848/171930255-c0a8b7b1-54e3-4fc3-a58b-a4cbd34313bc.png)

**Comment by JustDarker** [comment] 2022-06-03 19:33
It could be demo mod bug, we need to test it in a normal lobby

**Comment by NMOTH** [comment] 2022-06-03 19:36
> It could be demo mod bug, we need to test it in a normal lobby

that is what I assumed as well. but haven't had a chance to test normal lobby.

**Comment by BenjinZA** [comment] 2022-06-03 20:40
Tested in private lobby, same behaviour.

![image](https://user-images.githubusercontent.com/43580848/171949084-44f14ef4-0d5f-49be-86fb-9fa7baec7556.png)

**Comment by JustDarker** [comment] 2022-06-05 09:55
> Tested in private lobby, same behaviour.
> 
> ![image](https://user-images.githubusercontent.com/43580848/171949084-44f14ef4-0d5f-49be-86fb-9fa7baec7556.png)

And again, DK don't have Linken, ingame behavior and combat log is just right

**Comment by BenjinZA** [comment] 2022-06-05 19:44
@JustDarker Combat log states how Dragon Knight should lose 52 HP (70 damage form level 1 Dragon Tail less 25% resistance = 52.5), but you can see that Dragon Knight has 517 HP. He was on 515 HP after reflecting level 1 Dragon Tail from full HP (140 damage less 25% resistance = 105 damage), the 517 HP is just because I was waiting on combat log to update.

The damage is being applied twice, which means Dragon Tail is reflected twice.

**Comment by TheUnholyWrath** [comment] 2022-08-10 07:19
https://user-images.githubusercontent.com/46859977/183838950-e8fac458-9240-4f3e-bee9-d0759f69db3c.mp4

You can use hood to block some of the damage so it shows up properly in the combat log.

**Comment by Dota-Exp** [comment] 2022-10-05 19:35
Will be fixed in an upcoming update, thank you.

**Closed by Dota-Exp** 2022-10-05 19:35 UTC
