### ISSUE TITLE
Issue with Invokers spell details

### ISSUE THREAD

**Issue by 666Whitelotus666** [ValveSoftware/Dota2-Gameplay#9108] opened 2023-05-10 02:54 UTC
### Hero and spell

Invoker (All the spells with details)

### Description

Invoker shows more details of the skill than you can level for example there are a total 7 points for Quas and the skill cold snap details shows 8 cold snap duration parts this is same for all the other skills of invoker. They all have 8 parts showing the details when there is only 7 points

**Comment by irismus** [comment] 2023-05-10 04:45
Not a bug. All invoked spells have 8 levels by default. The 8th level is unlocked with Scepter.

**Comment by TheUnholyWrath** [comment] 2023-05-16 13:01
You can close this issue.

**Closed** 2023-05-16 13:04 UTC
