### ISSUE TITLE
keeper of  the light skill can not be refresh

### ISSUE THREAD

**Issue by wangziheng0426** [ValveSoftware/Dota2-Gameplay#13601] opened 2023-11-18 20:34 UTC
### Description

keeper of  the light skill can not be refresh by the Ex Machina

when i clicked the item my skills is still colling down

### Example Match ID (and possibly Timestamp)

7446347381  31:5

**Comment by LokeLok** [comment] 2023-11-18 21:41
Not a bug. Ex Machina only refreshes Items not Abilities. Please close this issue.

**Closed** 2023-11-19 02:55 UTC
