### ISSUE TITLE
Flickering minimap icons with dota_minimap_hero_scalar 1

### ISSUE THREAD

**Issue by caboyd** [ValveSoftware/Dota2-Gameplay#11031] opened 2023-08-30 23:06 UTC
### Description

With `dota_minimap_hero_scalar 1`, the minimap hero icons flicker in size.

My dota values.

`dota_minimap_hero_size 796.551758`
`dota_minimap_hero_scalar 1`

### Screenshots

https://github.com/ValveSoftware/Dota2-Gameplay/assets/10170577/989f1e80-93ea-4c05-8109-eed5adeb93fc

**Comment by OliverHenrichs** [comment] 2023-08-30 23:37
Can confirm. 
Reducing minimap hero size fixes it (threshold around 77-79%) . 
Does not occur with hero icons. 
Is independent of other options in the minimap category.

**Comment by bobjoe400** [comment] 2023-08-31 00:48
Same here. 

Thought it was related to fps, as I was running >240 fps. However using,
`fps_max 60` 
results in the same effect at a hero icon scale greater than 79% as when I use, 
`fps_max 0`

**Comment by yurok0900** [comment] 2023-08-31 14:13
problem is in dynamic scale. Options ->To advanced options -> Dynamically Scale Hero icon in Minimap. If you disable this option, all will be correct

**Comment by bobjoe400** [comment] 2023-08-31 22:02
I like using dynamically scaled heroes on the minimap. I was able to have both before the patch. 

> problem is in dynamic scale. Options ->To advanced options -> Dynamically Scale Hero icon in Minimap. If you disable this option, all will be correct

**Comment by hai-ben** [comment] 2023-08-31 22:06
Happens to me as well.

**Comment by jjnusnuff** [comment] 2023-08-31 23:08
same issue after cache update. disabling dynamic scale works. for now.

**Comment by iTRUEoGod** [comment] 2023-09-20 18:58
Still experiencing the issue. As before none of the other suggested fixes work for me. 

Others still having issue?

**Comment by iTRUEoGod** [comment] 2023-09-23 19:01
Thanks Plat! That did the job.

`dota_minimap_hero_scalar 1`  - still flickering

`dota_minimap_hero_spread 0` + `dota_minimap_hero_scalar 0` no flickering

**Comment by bobjoe400** [comment] 2023-09-23 22:04
Do you still get the intended behavior of having the arrows dynamically
size depending on the number of heroes around?

**Comment by iTRUEoGod** [comment] 2023-09-23 23:32
No, the arrows do not dynamically scale.

Turning on that option (`dota_minimap_hero_scalar 1`) the arrows start to flicker again. 

Having both set to 0 is what stopped the flicker

**Comment by bobjoe400** [comment] 2023-09-24 00:27
That is the issue that we are trying to fix here.

This behavior worked before the patch and is important to me.

**Comment by eugene-valve** [comment] 2023-10-11 17:48
Thanks everyone for the detailed information, the video footage was especially helpful. This should be fixed in an upcoming update!

**Closed by eugene-valve** 2023-10-11 17:48 UTC
