### ISSUE TITLE
Primal Beast Ultimate Skill Bug

### ISSUE THREAD

**Issue by ZerstorerX** [ValveSoftware/Dota2-Gameplay#6817] opened 2023-02-01 06:03 UTC
### Ability name

Pulverize

### Description

Primal Beast Ultimate only does 1 stomp then cancel itself for no reason

Video: https://youtu.be/IXaD91YcTUU

### Example Match ID (and possibly Timestamp)

6996489952

**Comment by shaileshgarg** [comment] 2023-02-01 06:06
https://github.com/ValveSoftware/Dota2-Gameplay/issues/6815

**Comment by HashJProgramming** [comment] 2023-02-01 06:57
same here, I thought I'm the only one encounter this bug

**Comment by huynh268** [comment] 2023-02-01 07:19
I just faced the same issue.

**Comment by smmarius** [comment] 2023-02-01 12:12
Guys please use the search option to see if your issue is already posted by someone else. Eventually add there more details if needed in the comments. 
Duplicate of:  #6815

**Comment by Dota-Exp** [comment] 2023-02-01 21:55
Fix is live. Thank you

**Closed by Dota-Exp** 2023-02-01 21:55 UTC
