### ISSUE TITLE
Overwatch Crash (repeatable)

### ISSUE THREAD

**Issue by KatiePup** [ValveSoftware/Dota2-Gameplay#8330] opened 2023-04-22 09:46 UTC
### Description

Screenshot shows Error popup when loading overwatch case, the game crashes when it's clicked.

### Screenshots

![image](https://user-images.githubusercontent.com/74455738/233776458-c5b9a426-5d9f-4df1-bbaf-a7aba2ae038b.png)

**Comment by criptoluiz** [comment] 2023-04-22 12:31
Same happening here since patch came out yesterday, repeatable and can't watch any overview replay as result.
I'm on a ryzen 3 with vega 8 graphics and 23.4.1 adrenalin drivers, if that's of any help. :)


![image](https://user-images.githubusercontent.com/24922036/233784873-ac0a9cc2-1471-4891-b1a9-3870e7cad4fd.png)

**Comment by pontuslaestadius** [comment] 2023-04-23 06:58
Duplicate of #8183 please close and upvote the existing ticket.

**Comment by Nathanael-Valve** [comment] 2023-05-22 22:59
Fixed

**Closed by Nathanael-Valve** 2023-05-22 22:59 UTC
