### ISSUE TITLE
Revealing Monkey King's Mischief from fog of war causes the entire enemy team to crash

### ISSUE THREAD

**Issue by mjbcopland** [ValveSoftware/Dota2-Gameplay#11429] opened 2023-09-03 10:01 UTC
### Ability name

Mischief

### Description

Sometimes, if Monkey King uses Mischief in fog of war, then enters vision of the enemy team, the entire enemy team will crash-to-desktop when MK becomes visible. This can happen either by MK moving into existing vision or the enemy team expanding their vision.

After a few seconds the disconnection is recognised for all five players but there is no auto-pause nor poor network detected etc.

I doubt it happens every time a mischiefed monkey crosses the fog of war boundary, otherwise we would be seeing it happen a lot more often. However, this does appear to be the one consistency between the three examples I have included. In each example I have enabled fog of war for the opposing team to MK to demonstrate the behaviour.

### Example 1: 7316439780 - 32:56

Radiant Monkey King uses Mischief in his team's fountain, and is hidden by fog of war because the fountain area is highground. When Dire enter the fountain area and consequently provide vision of MK, all five dire players instantly and simultaneously crash. This is particularly obvious as all players stop moving. Each affected player disconnects a few moments later.

https://github.com/ValveSoftware/Dota2-Gameplay/assets/16596696/2811c95b-bc15-4b4f-912d-2c001069e57e

### Example 2: 7316449822 - 38:04

Dire Monkey King is preparing to defend his Tier 3 tower and uses mischief on the edge of his highground. When Radiant push up and reveal MK, again all five players instantaneously crash and stop moving.

https://github.com/ValveSoftware/Dota2-Gameplay/assets/16596696/68f47d48-c1e4-4446-bb79-79d18ea7db98

### Example 3: 7316457937 - -0:27

Dire Monkey King uses Mischief to walk along mid lane. When MK reaches the river and enters Radiant vision, all Radiant players crash and disconnect moments later. The camera here is focused on the river to show that the affected players do not have to interact with MK, nor do they even have to be looking at MK, only that MK must enter vision while using Mischief.

https://github.com/ValveSoftware/Dota2-Gameplay/assets/16596696/60522ada-0bd5-4793-a153-c4707b9e8275

### Example Match ID (and possibly Timestamp)

7316439780 - 32:56, 7316449822 - 38:04, 7316457937 - -0:27

**Comment by mjbcopland** [comment] 2023-09-03 10:21
Some more quick testing; when MK uses Mischief, the ability changes to Revert Form. When MK uses Mischief in fog, the enemy can't see that the ability has changed. This makes sense, but means that it is only revealed when MK re-enters vision. I wonder if this is related.

https://github.com/ValveSoftware/Dota2-Gameplay/assets/16596696/8e4b5f29-7871-484d-876e-7f53737fe40f

**Comment by meunleashed** [comment] 2023-09-03 17:42
also encountered this bug twice in this match (ID: 7317915646)
I think your suspecion is correct.

**Comment by shubhrathi** [comment] 2023-09-09 01:53
I got it that this bug related to monkey king but how do you explain this?

https://m.youtube.com/watch?v=Q9zpZv3EV7k

There is no monkey king in the game. Match id: 7325887289
I think this bug can be abused without mk also.

All the above information taken from recent reddit post: https://reddit.com/r/DotA2/s/5hadKQ4z1T

**Comment by shubhrathi** [comment] 2023-09-09 02:05
I think valve should implement feature that game auto pause if all five players of either dire or radiant disconnects and opposing team can only unpause if atleast one player fully connected or even better option make it safe to leave and not counted towards mmr

**Comment by Gol0vach** [comment] 2023-09-09 16:12
This is not a bug of MK, this is a DDoS of the Steam servers and an abuse of the rating
https://www.twitch.tv/lenagol0vach/clip/TangentialEnjoyableShallotHeyGuys-rqERhPkjkYzlKiYT
https://www.twitch.tv/lenagol0vach/clip/RoughNeighborlyRingStoneLightning-fi2vY2GzCWaD-abO
https://www.twitch.tv/lenagol0vach/clip/GrotesqueClearChowderDerp-pRwNtenBSri0IL3-

**Comment by meunleashed** [comment] 2023-09-09 17:16
> This is not a bug of MK, this is a DDoS of the Steam servers and an abuse of the rating https://www.twitch.tv/lenagol0vach/clip/TangentialEnjoyableShallotHeyGuys-rqERhPkjkYzlKiYT https://www.twitch.tv/lenagol0vach/clip/RoughNeighborlyRingStoneLightning-fi2vY2GzCWaD-abO https://www.twitch.tv/lenagol0vach/clip/GrotesqueClearChowderDerp-pRwNtenBSri0IL3-

calm down. what you are refering to is another totally different matter. MK is indeed bugged

**Comment by BannZay** [comment] 2023-09-10 23:26
Same happened to me. mk used mischief out of vision and game crashed right after he became visible, whole our team got disconnected.


https://github.com/ValveSoftware/Dota2-Gameplay/assets/17499770/e07883d1-8981-40d0-b88f-f4bf7e3f80f5



https://www.dotabuff.com/matches/7329346810

**Comment by palaganaskurl** [comment] 2023-09-11 18:54
Encountered this also match ID 7330546728 around 27 mins

**Comment by vookhan** [comment] 2023-09-11 21:40
Match ID: 7330647824, minute 55

https://www.reddit.com/r/DotA2/comments/16g6jqa/our_whole_team_disconnected_minute_55_before/

sad

**Comment by InfestedNexus** [comment] 2023-09-13 23:23
Match ID 7333666174

**Comment by eugene-valve** [comment] 2023-09-14 17:40
Thank you everyone for the details bug report and information. This bug should be fixed in the next update.

**Closed by eugene-valve** 2023-09-14 17:40 UTC
