### ISSUE TITLE
Movespeed bug

### ISSUE THREAD

**Issue by VanilllaPutin** [ValveSoftware/Dota2-Gameplay#12378] opened 2023-09-30 18:57 UTC
### Description

Wraith king started with 345 movespeed in e first 40 seconds of the game. Did not seem like it was only a visual bug.

### Example Match ID (and possibly Timestamp)

7356924032

**Comment by LokeLok** [comment] 2023-09-30 19:19
Not a bug.

Taken from 7.33 patch notes: All units now gain 15 movement speed during the night. Effect is doubled for heroes, but it can be broken for 5 seconds upon attacking or taking damage from player-controlled sources (similar to Tranquil Boots)

Please close this issue.

**Closed** 2023-09-30 20:00 UTC
