### ISSUE TITLE
Alt+Clicking the "Lit" buff of a Watcher crashes the game

### ISSUE THREAD

**Issue by Steffo99** [ValveSoftware/Dota2-Gameplay#8181] opened 2023-04-21 15:08 UTC
### Description

Seems very similar to a bug that was happening in last Aghanim's Labyrinth which manifested itself in the same way (alt+clicking certain enemy unit buffs); in that case, the bug crashed **all Linux players connected to the game**.

Given that I am myself playing on Linux, and that my teammates didn't crash when that buff was pinged, I suspect that **the bug is exclusive to the Linux build of the game**, but I currently have no way to verify if this is happening on other platforms.

### How to reproduce

1. Click on a captured Watcher
2. Hover the "Lit" buff
3. Hold <kbd>Alt</kbd> and click <kbd>Left Mouse Button</kbd>
4. Game crashes

### Example Match ID (and possibly Timestamp)

7117450836

**Comment by ybabts** [comment] 2023-06-11 03:49
Duplicate of #8160

**Closed** 2023-06-11 15:40 UTC
