### ISSUE TITLE
Dota 2 won't load after battlepass update

### ISSUE THREAD

**Issue by stelikz** [ValveSoftware/Dota2-Gameplay#2632] opened 2022-09-02 01:54 UTC
### Description

Dota 2 won't load while on macbook

macOS Monterey, 12.5.1

**Comment by Varun271** [comment] 2022-09-02 02:11
Dota 2, icon comes on screen and after a while not responding, i tried running it with all the possible launch options still the same result, "not responding" in mac. I even updated my mac OS.

**Comment by nikelsk8** [comment] 2022-09-02 02:52
> Dota 2, icon comes on screen and after a while not responding, i tried running it with all the possible launch options still the same result, "not responding" in mac. I even updated my mac OS.

ME TOO...to do?

**Comment by Varun271** [comment] 2022-09-02 03:40
<img width="999" alt="Screen Shot 2022-09-01 at 11 40 17 PM" src="https://user-images.githubusercontent.com/65506707/188054583-754d3b27-9cf7-45ed-a2cd-309a55bc5de8.png">
i have placed a image for reference.

**Comment by brocva** [comment] 2022-09-02 06:35
OMG SAME HERE!!! PLEASE HELP

**Comment by longd3** [comment] 2022-09-02 06:48
Surprise me. So disappointing

**Comment by yp-palF** [comment] 2022-09-02 08:13
Same, happening with me as well

**Comment by Dedalus-Stephen** [comment] 2022-09-02 10:13
same

**Comment by RiggyZoo** [comment] 2022-09-02 11:02
Same with me. I've tried to reinstall the game but still I have the same issue

**Comment by nenadwb** [comment] 2022-09-02 11:13
What's going on? I tried multiple launch options but nothing works. Reinstalled game twice and still nothing. Does someone know wassup?

**Comment by dobstotev** [comment] 2022-09-02 11:34
OMG same for me, exactly the same problem!

**Comment by dabdraimov** [comment] 2022-09-02 11:35
Please, fix it ASAP, same issue

**Comment by Afshibidar** [comment] 2022-09-02 11:51
I have it on macbook air 2016 as well and it is not responding, i think we need to wait for them to make it ok

**Comment by testadsasda23** [comment] 2022-09-02 12:03
The same

**Comment by jesusPoveda** [comment] 2022-09-02 12:43
Same here

**Comment by MariusRossouw** [comment] 2022-09-02 12:58
Same here. Reinstalled Dota but it did not work. Tried different launch options but none of them worked. What I have noticed is that if I use -vulkan the game crashes without even loading the Dota image. If I use -gl instead of -vulkan I at least get the Dota logo but it still hangs. Any help will be much appreciated. Thank you in advance

**Comment by RoeelCohen** [comment] 2022-09-02 13:10
same

**Comment by vkravchik** [comment] 2022-09-02 13:16
The same for me MacOS 12.5.1 (21G83)

**Comment by amy2488** [comment] 2022-09-02 13:34
i have the same issue. not able to see dota 2 icon when its launching its keep on circling.

**Comment by shadowalker77** [comment] 2022-09-02 13:46
Every update on mac, has some issues. Do they even test the game before launching it?

**Comment by dobstotev** [comment] 2022-09-02 13:48
> Every update on mac, has some issues. Do they even test the game before launching it?

I don't think they have Macs :D haha probably was tested on a virtual Mac machine where it worked :D but things are different between virtual and real one haha.

**Comment by DivOfMoD** [comment] 2022-09-02 13:51
The same problem, dota 2 not opening after battle pas 2022 update.
OS: macOS Monterey 
Device: MacBook Pro (16-inch, 2019)
Memory: 16 gb ddr4
Graphics: AMD Radeon Pro 5300M 4 gb
Processor: 2,6 GHz Intel Core i7

@steam please help :(

**Comment by shadowalker77** [comment] 2022-09-02 13:53
It seems everyone here got Intel macs. Does M1 Macs got these problem too?

**Comment by DivOfMoD** [comment] 2022-09-02 13:59
Sent this tread's link to Steam's Support Team, no response yet

**Comment by Dedalus-Stephen** [comment] 2022-09-02 14:02
cant believe they havent fixed it yet wtf

**Comment by dobstotev** [comment] 2022-09-02 14:13
> It seems everyone here got Intel macs. Does M1 Macs got these problem too?

That's an interesting question. Mine is NOT an M1 atm.

**Comment by knigadima** [comment] 2022-09-02 14:15
Hey 

The same problem, Dota 2 not opening after battle pas 2022 update. Reinstalled Dota but it did not work :(

OS: macOS Catalina 10.15.7
Device: MacBook Air (13-inch, 2017)
Memory: 8 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 6000 1536 MB
Processor: 1,8 GHz double core Intel Core i5

@steam please help guys

**Comment by lazyKT** [comment] 2022-09-02 14:26
Any update guys?

**Comment by dobstotev** [comment] 2022-09-02 14:37
I think we should get a fix by the end of the day (US timezone) I am sure they are working on it.

**Comment by bi0morph** [comment] 2022-09-02 14:41
> I think we should get a fix by the end of the day (US timezone) I am sure they are working on it.
Hope so 👍

**Comment by lazyKT** [comment] 2022-09-02 14:49
> I think we should get a fix by the end of the day (US timezone) I am sure they are working on it.

Hopefully. 🫣

**Comment by petrov-pavel** [comment] 2022-09-02 14:51
Same here. Please fix it asap! 
macOS Monterey 12.5.1 (21G83)
MacBook Pro (16-inch, 2019) C02FW13AMD6P

**Comment by mabhijith04** [comment] 2022-09-02 15:08
Same here

**Comment by espisangijo** [comment] 2022-09-02 15:12
same here

**Comment by thuliumsystems** [comment] 2022-09-02 15:14
i have tried open dota using terminal with this command: 
exec ~/Library/Application\ Support/Steam/steamapps/common/dota\ 2\ beta/game/dota.sh

i got these errors
<img width="2037" alt="Screen Shot 2022-09-02 at 11 06 12 AM" src="https://user-images.githubusercontent.com/49157990/188178908-0bf76d04-858c-436f-aada-9dc763cb85e5.png">

i installed cairo using homebrew, but still not working...

**Comment by n0k8t** [comment] 2022-09-02 15:16
> I think we should get a fix by the end of the day (US timezone) I am sure they are working on it.

Sounds nice. But as we see no response from Valve at all(when they started to communicate with audience in last years) I think it's not likely. 

Ps why I said about response, bc it is a major issue, ofc Mac users are not 50+% but still a significant amount can't open a game.

**Comment by dobstotev** [comment] 2022-09-02 15:20
I think they know about it (from Steam discussion forum and all support tickets raised to Steam from players)

**Comment by JeffreyCheong** [comment] 2022-09-02 15:23
Same here

**Comment by richardlim08** [comment] 2022-09-02 15:27
Same here, it sucks 'cause I kinda wanted to play over the weekend!

**Comment by dennich** [comment] 2022-09-02 15:31
Same here

**Comment by abelernesto** [comment] 2022-09-02 15:39
same error 
MacBook Pro (16-inch, 2019)

**Comment by TristanHW** [comment] 2022-09-02 15:41
I have had the same issue all day on my macbook pro 2018. until one time it worked and I got into the lobby about an hour ago. I then restarted my computer because I have some fan issues (and kernel_task...) so the game basically only works right after startup. same issue with black screen and rainbow wheel since the restart.. so I didn't get to play.. 
but it seems interesting that it worked I think.

**Comment by bysobi** [comment] 2022-09-02 15:42
Same error Macbook pro 2017

**Comment by Varun271** [comment] 2022-09-02 15:44
Probably an intern rolled out this update :)

**Comment by antonsmiiukha** [comment] 2022-09-02 15:45
It's working fine, I don't see what the problem is.
MacBook Pro 2019 intel

**Comment by cryptolove123** [comment] 2022-09-02 15:47
Any ETA on this fix?

**Comment by RomanCoding** [comment] 2022-09-02 15:47
> It's working fine, I don't see what the problem is. MacBook Pro 2019 intel

and you even can see Battlepass ingame?

**Comment by Dedalus-Stephen** [comment] 2022-09-02 16:24
steam downloaded something twice in the last 30 mins but neither of updates contained the fix

**Comment by Varun271** [comment] 2022-09-02 16:47
i dont know when will they roll out the update....and optimize dota for mac users.

**Comment by lazyKT** [comment] 2022-09-02 16:58
Still no updates? Really disappointed. I was aiming to play during the whole weekend. 🤦🏽‍♂️🤦🏽‍♂️🤦🏽‍♂️

**Comment by RomanCoding** [comment] 2022-09-02 17:29
update was downloaded, but still no success

**Comment by NalinikanthMeesala0201** [comment] 2022-09-02 17:32
> i have tried open dota using terminal with this command: exec ~/Library/Application\ Support/Steam/steamapps/common/dota\ 2\ beta/game/dota.sh
> 
> i got these errors <img alt="Screen Shot 2022-09-02 at 11 06 12 AM" width="2000" src="https://user-images.githubusercontent.com/49157990/188178908-0bf76d04-858c-436f-aada-9dc763cb85e5.png">
> 
> i installed cairo using homebrew, but still not working...
> 
> <img alt="Screen Shot 2022-09-02 at 11 15 42 AM" width="223" src="https://user-images.githubusercontent.com/49157990/188180757-ed4408e6-d6ed-4c8b-b2a3-6e8ff809d43b.png">

There is no libcairo.dylib but there is cairo.dylib

**Comment by Varun271** [comment] 2022-09-02 17:34
not working for me either, yesterday i switched to opengl, for a moment the dota cursor came and then it stopped, after that whenever i launch i can see the normal mac cursor and it stops.

**Comment by chanchan04** [comment] 2022-09-02 17:35
Hi  guys , have you tried using launch options -novid? I tried it just now and it worked. 

![image](https://user-images.githubusercontent.com/112721838/188207767-0306a7b0-eeca-4927-889f-0956369d88de.png)

**Comment by RomanCoding** [comment] 2022-09-02 17:38
> Hi guys , have you tried using launch options -novid? I tried it just now and it worked.
> 
> ![image](https://user-images.githubusercontent.com/112721838/188207767-0306a7b0-eeca-4927-889f-0956369d88de.png)

didn't help, sadly :(

Macbook Pro 16'

**Comment by souljorje** [comment] 2022-09-02 17:38
@chanchan04 didn't help as well, MBP 15

**Comment by Varun271** [comment] 2022-09-02 17:39
not working for me either

**Comment by chanchan04** [comment] 2022-09-02 17:39
hopefully they can fix this asap :(

**Comment by dennich** [comment] 2022-09-02 17:40
> -novid

no luck for me

**Comment by m-waqar-shahid** [comment] 2022-09-02 17:44
### Same for me. 😢 It was running perfectly fine until battle pass update of last night.

**System Information:**

Model Name: MacBook Pro
Model Identifier: MacBookPro16,2
Processor Name: Quad-Core Intel Core i5
Processor Speed: 2 GHz
Number of Processors: 1
Total Number of Cores: 4
L2 Cache (per Core): 512 KB
L3 Cache: 6 MB
Hyper-Threading Technology: Enabled
Memory: 16 GB
System Firmware Version: 1731.140.2.0.0 (iBridge: 19.16.16066.0.0,0)
OS Loader Version: 540.120.3~19
Serial Number (system): C02FD5VSML7H
Hardware UUID: 3A66632F-5D35-5842-853A-AC2F9C149FCE
Provisioning UDID: 3A66632F-5D35-5842-853A-AC2F9C149FCE
Activation Lock Status: Disabled

**Comment by thuliumsystems** [comment] 2022-09-02 17:45
> 

open finder and search this: libcairo.dylib

**Comment by Varun271** [comment] 2022-09-02 17:47
> > 
> 
> open finder and search this: libcairo.dylib

and after then?

**Comment by thuliumsystems** [comment] 2022-09-02 17:48
look this picture: https://github.com/ValveSoftware/Dota2-Gameplay/issues/2632#issuecomment-1235620987

**Comment by Varun271** [comment] 2022-09-02 17:50
> look this picture: [#2632 (comment)](https://github.com/ValveSoftware/Dota2-Gameplay/issues/2632#issuecomment-1235620987)

got your point that file is missing i guess

**Comment by shadowalker77** [comment] 2022-09-02 17:52
I think that's not the issue. I managed to run the game randomly (three times) even with this error. But it won't run again after that. I can confirm that this file is missing on my Mac, but still game ran three times.

**Comment by Varun271** [comment] 2022-09-02 17:53
> I think that's not the issue. I managed to run the game randomly (three times) even with this error. But it won't run again after that. I can confirm that this file is missing on my Mac, but still game ran three times.

i managed to get dota cursor once and it stopped..

**Comment by shadowalker77** [comment] 2022-09-02 17:56
I even made it through watching a game from bzm (lol). So, vulkan is not the issue since I was running the game using it. This missing file is not the issue since I didn't have it. I think "libscenefilecache.dylib" file is causing the issue, since game stuck on loading it.

**Comment by shadowalker77** [comment] 2022-09-02 17:57
If you managed to enter the game, DO NOT try to open a treasure, it will stop working just like game startup.

**Comment by cryptolove123** [comment] 2022-09-02 18:07
@jeffhill Any updates here?

**Comment by DivOfMoD** [comment] 2022-09-02 18:17
> Hi guys , have you tried using launch options -novid? I tried it just now and it worked.
> 
> ![image](https://user-images.githubusercontent.com/112721838/188207767-0306a7b0-eeca-4927-889f-0956369d88de.png)

I succeed opening dota 2 with this option, but then it freezed in the game xD 
<img width="1536" alt="Снимок экрана 2022-09-02 в 21 12 24" src="https://user-images.githubusercontent.com/28047665/188214054-583b5e13-bc81-4d67-80c9-4a47b027cf65.png">

**Comment by Bych** [comment] 2022-09-02 18:30
Not working for me as well.

macOS Monterey 12.5.1
MacBook Pro (15-inch, 2019)
Processor 2,3 GHz 8-Core Intel Core i9
Memory 16 GB 2400 MHz DDR4

**Comment by richardlim08** [comment] 2022-09-02 18:31
Still no luck.

**Comment by ivanserendipity** [comment] 2022-09-02 18:58
Hey, its been a day, when will we fix this? My wallet is ready

macOS Monterey 12.5.1
Processor 3 GHz 6-Core Intel Core i5
Memory 8 GB 2667 MHz DDR4
Graphic Intel UHD Graphics 630 1536 MB

**Comment by Testinis297** [comment] 2022-09-02 19:00
This worked for me
"-noprewarm -novid -safe_mode -vulkan"
But as for everyone, froze when match has started

**Comment by petrov-pavel** [comment] 2022-09-02 19:02
> This worked for me "-noprewarm -novid -safe_mode -vulkan" But as for everyone, froze when match has started

tryed, not working at all

**Comment by Tycho-Ext** [comment] 2022-09-02 19:06
> It seems everyone here got Intel macs. Does M1 Macs got these problem too?

Yes M1 MacBook is also affected.

**Comment by richardlim08** [comment] 2022-09-02 19:10
> This worked for me "-noprewarm -novid -safe_mode -vulkan" But as for everyone, froze when match has started

Worked for me once, I tried restarting dota and got the same issue again.

**Comment by ivanserendipity** [comment] 2022-09-02 19:15
> This worked for me "-noprewarm -novid -safe_mode -vulkan" But as for everyone, froze when match has started

Thanks, it works once for me but failed the second time.

""-noprewarm -novid -safe_mode" this works after second time

**Comment by richardlim08** [comment] 2022-09-02 19:17
> > This worked for me "-noprewarm -novid -safe_mode -vulkan" But as for everyone, froze when match has started
> 
> Thanks, it works once for me but failed the second time.
> 
> ""-noprewarm -novid -safe_mode" this works after second time

Thanks, but I tried and unfortunately it doesn't seem to work for me.

**Comment by dobstotev** [comment] 2022-09-02 19:17
> 

Doesnt work for me either

**Comment by Varun271** [comment] 2022-09-02 19:19
most of the mac users are having problems after update.

**Comment by berkcirisci** [comment] 2022-09-02 19:21
> 

After each update with battlepass really

**Comment by mrsnax** [comment] 2022-09-02 19:26
oh god... still not updated until right now :(

**Comment by wassgang93** [comment] 2022-09-02 19:33
They are saying it’ll be fixed by Monday.

**Comment by okolesnichenko** [comment] 2022-09-02 19:34
> After each update with battlepass really

where? prof

**Comment by lazyKT** [comment] 2022-09-02 19:34
> They are saying it’ll be fixed by Monday. 

Sh*t man, then what're we supposed to do this weekend ☹️

**Comment by okolesnichenko** [comment] 2022-09-02 19:35
> They are saying it’ll be fixed by Monday.

Can you show where they saying it?

**Comment by Varun271** [comment] 2022-09-02 19:35
> They are saying it’ll be fixed by Monday.

r u kidding me, i love this game but sometimes i just feel like deleting it

**Comment by DmitrySemenyk** [comment] 2022-09-02 19:37
> They are saying it’ll be fixed by Monday.

give them one hour.....or delete the game! 🍑

**Comment by mohammadain** [comment] 2022-09-02 19:45
Still no luck guys? guardian here

**Comment by EgorKazachenko** [comment] 2022-09-02 20:00
bump

**Comment by vladimirYa** [comment] 2022-09-02 20:12
Same. Bruh, it is ruined my evening. shit...

**Comment by wassgang93** [comment] 2022-09-02 20:14
Guys they have acknowledged the bug it’ll be back on Monday. 12th Sept 2022

**Comment by okolesnichenko** [comment] 2022-09-02 20:17
> Can you show where they saying it?

Can you show where they saying it?

**Comment by okolesnichenko** [comment] 2022-09-02 20:18
> Guys they have acknowledged the bug it’ll be back on Monday. 12th Sept 2022

Can you show where they saying it?

**Comment by fatagun** [comment] 2022-09-02 20:42
i uninstall and installed 3 times, with cleaning the file system and everything. 

This is pathetic! Nobody tests this software?

**Comment by vladimirYa** [comment] 2022-09-02 20:45
LETS FUCKING SPAM THEN!!!!!!

**Comment by vladimirYa** [comment] 2022-09-02 20:46
I WANT THEM TO SUFFER AS WE ARE!

**Comment by Varun271** [comment] 2022-09-02 20:47
they better give us some cool free stuff. This is pathetic coming from one of the biggest game out there.

**Comment by ipixby** [comment] 2022-09-02 21:00
Same issue.

Startup options **-novid -console**

Use **Vulcan**

<img width="1440" alt="Screen Shot 2022-09-03 at 00 59 45" src="https://user-images.githubusercontent.com/5840884/188234509-3c024091-0baf-4a64-9b7d-90216fbe2a05.png">

Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro10,1
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:        Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2700 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.15.7 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 4000
    Driver Version Not Detected
    OpenGL Version: 4.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x8086
    DeviceID:  0x166
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 13.03" x 8.11" (15.31" diag)
                                            33.1cm x 20.6cm (38.9cm diag)
    Primary VRAM: 1536 MB

Memory:
    RAM:  16384 MB

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  1192420 MB
    Largest Free Hard Disk Block:  218422 MB

Storage:
    Number of SSDs: 0
    Number of HDDs: 0

**Comment by Dedalus-Stephen** [comment] 2022-09-02 21:04
> cant believe they havent fixed it yet wtf

this is ridiculous

**Comment by mohsinka** [comment] 2022-09-02 21:05
@ipixby developer at work! Nice 🤩
New update is here, hopefully that will resolve, lets see

**Comment by mohsinka** [comment] 2022-09-02 21:09
UGH!! No LUCK!! 👎

**Comment by SergejFrank** [comment] 2022-09-02 21:09
> @ipixby developer at work! Nice 🤩 New update is here, hopefully that will resolve, lets see

nope

**Comment by Dedalus-Stephen** [comment] 2022-09-02 21:09
i wonder what miscellaneous stuff they patched in this 100 mb right now, ignoring that it doesnt run for a whole platform

**Comment by dobstotev** [comment] 2022-09-02 21:12
Yeah new update is not working for me either

**Comment by fatagun** [comment] 2022-09-02 21:16
nothing is working. ruined my weekend.

**Comment by ilongross** [comment] 2022-09-02 21:16
same
mac intel

**Comment by mohsinka** [comment] 2022-09-02 21:18
Time to move to something else then, what say this: 
https://steampeek.hu/?appid=386360#gdetails
OR
https://steampeek.hu/?appid=235340#gdetails

?

**Comment by fbandrey** [comment] 2022-09-02 21:20
> Time to move to something else then, what say this: https://steampeek.hu/?appid=386360#gdetails OR https://steampeek.hu/?appid=235340#gdetails
> 
> ?

https://solitaired.com/

**Comment by Dedalus-Stephen** [comment] 2022-09-02 21:24
https://sketchful.io/room/1ukcr

**Comment by thuliumsystems** [comment] 2022-09-02 21:28
They just released an update, but still not working... unbelievable...

**Comment by fatagun** [comment] 2022-09-02 21:32
well i am losing hope. i think it is xhamster time.

**Comment by SyncKid** [comment] 2022-09-02 21:34
Keep the faith does not work on imac 😢

**Comment by Dedalus-Stephen** [comment] 2022-09-02 21:47
https://sketchful.io/room/1ukcr

**Comment by mohsinka** [comment] 2022-09-02 21:59
@Dedalus-Stephen i was dotanoob. WP! 🥇

**Comment by Dedalus-Stephen** [comment] 2022-09-02 22:00
> 

ahahah wp bro

**Comment by mohsinka** [comment] 2022-09-02 22:02
I so envy the shit windows users rn! 😡

**Comment by Sheaffy** [comment] 2022-09-02 22:12
Can confirm, just got the update and has bricked Dota on macOS 12.4, Intel i7.
Same symptoms as described in issue, blank screen on the start up of the game with loading cursor.

**Comment by Dedalus-Stephen** [comment] 2022-09-02 22:17
https://sketchful.io/

we have vacant places now

**Comment by smh-freelancer** [comment] 2022-09-02 22:39
Same issue.
hackintosh monterey.

Startup options :
-vulkan -vconsole   => not start & show Nothing 

with 

-gl   => not start & show dota2 logo

----------------------- 
last week whit hackintosh big sur everything was working fine.

**Comment by HiroAsashi** [comment] 2022-09-02 22:51
Same issue Mac OS 11.6.8

**Comment by n0k8t** [comment] 2022-09-02 23:01
MacOS Monterey 12.3.1
MacBook Pro 2017 (15-inch) 
Intel

Same. Only Dota logo on gl, nothing on Vulcan

**Comment by Mikimo153** [comment] 2022-09-02 23:11
> cant believe they havent fixed it yet wtf

It usually takes them 2-3 days to fix it.

**Comment by Yeleshing** [comment] 2022-09-02 23:18
STILL DOESN'T WORK.

**Comment by SyncKid** [comment] 2022-09-02 23:37
please provide updates has anyone seen any improvement?

**Comment by su33u1411** [comment] 2022-09-03 00:21
any ETA ?

**Comment by wassgang93** [comment] 2022-09-03 00:36
[danginsburg](https://github.com/danginsburg) commented [9 minutes ago](https://github.com/ValveSoftware/Dota2-Gameplay/issues/2632#issuecomment-1236000031)
We finally got this figured out. It was a tricky problem due to a change in our low level memory allocator and it didn't repro on most of our machines. Fix is checked in, it will be in the next update.

**Comment by Nathanael-Valve** [comment] 2022-09-03 01:07
Per Dan, I'm currently in the process of shipping this.

**Closed by Nathanael-Valve** 2022-09-03 01:07 UTC

**Comment by jeff-lei-teampay** [comment] 2022-09-03 01:21
this is really devastating, could pls post this update? today possible?
Any ETA?

**Comment by jeff-lei-teampay** [comment] 2022-09-03 01:24
Any ETA @Nathanael-Valve ?

**Comment by Nathanael-Valve** [comment] 2022-09-03 01:25
It's live now. That's what I meant by 'in the process of shipping'.

**Comment by jeff-lei-teampay** [comment] 2022-09-03 01:26
you mean, it is already fixed? @Nathanael-Valve

**Comment by pro-nutty** [comment] 2022-09-03 01:26
Seeing the issue on

Build ID: 9443101
Installed content updated Sept2, 2022 at 6:11PM PST

**Comment by jeff-lei-teampay** [comment] 2022-09-03 01:27
now it;s working. just updated the app. thanks @Nathanael-Valve

**Comment by Varun271** [comment] 2022-09-03 02:18
thanks, its working

**Comment by mohsinka** [comment] 2022-09-03 04:51
Thank you @Nathanael-Valve & @wassgang93. We all know how a software becomes a showstopper. We appreciate your efforts. 🙏🎉🙌

**Comment by malipix** [comment] 2022-09-03 14:58
They fixed the issue with an update. But overall performance is so bad. Even if i reduce graphics to near 1080p i'm having 30 fps. On my bootcamp windows, i'm having 130-140 fps at 1080p.

**Comment by roamin-ronin** [comment] 2022-09-03 19:24
DotA plus assistant loads after about 12 minutes, and only loads partial suggestions

**Comment by thorizer** [comment] 2022-09-05 01:44
partially fixed, since this is closed upvote this issue instead  https://github.com/ValveSoftware/Dota2-Gameplay/issues/2749

**Comment by mohsinka** [comment] 2022-09-16 15:45
https://github.com/ValveSoftware/Dota2-Gameplay/issues/3162
