### ISSUE TITLE
Wraith King Skeletons ignore Clockwerk cogs

### ISSUE THREAD

**Issue by LulzyKing** [ValveSoftware/Dota2-Gameplay#13343] opened 2023-11-06 03:41 UTC
### Ability name

Vampiric Spirit

### Description

WK's Vampiric Spirit skeletons ignore collision from Clockwerk cogs and phase through them to hit you.

Happened basically every time cogs was used in match with WK nearby, unsure if this is intended gameplay interaction, as they seem to respect other barriers, ala Disruptor's Kinetic Field.

### Example Match ID (and possibly Timestamp)

7421785158

**Comment by irismus** [comment] 2023-11-06 04:41
**Power Cogs**
- Each cog has an 80-bound radius and is spawned 215 range away from Clockwerk, effectively blocking a 255-radius circle.
- All cogs are placed at a 164.5 range distance from each other. Together with their bound radius, the gap between the cogs is 4.5.
- Any unit with a bound radius ≥ 4.5 outside the circle or trapped within the center of the circle cannot move in or out respectively.

Wraith King Skeletons have a bound radius of 2.

**Kinetic Field**
On the other hand, Kinetic Field stops enemies by slowing them with a movement speed slow aura centered on the field and gets exponentially stronger towards the visible barrier, causing units to stop moving when being very close to the barrier.

Hope this helps! I do not think that these are bugs, just different ability/mechanic interactions.

**Comment by LulzyKing** [comment] 2023-11-06 21:43
Interesting, that would explain why they seem to ignore the cogs, appreciate the insight!

**Comment by irismus** [comment] 2023-11-06 22:39
Please close this issue since it is actually working as intended. Thanks!!

**Closed** 2023-11-07 04:47 UTC
