### ISSUE TITLE
Darkmoon mode, can't get gold bags

### ISSUE THREAD

**Issue by SnabrielSnarsch** [ValveSoftware/Dota2-Gameplay#2919] opened 2022-09-08 20:22 UTC
### Description

title says it all
you have to right-click the gold bags to get it instead of just walk over them (the radius is too tiny), it's really annoying
same with potions

### Example Match ID (and possibly Timestamp)

any

**Comment by tangalexd** [comment] 2022-09-08 21:55
I have a sample match ID 6747924573 and 6747908045. This really messes up the entire game mode and makes it nearly impossible to win.

**Comment by SnabrielSnarsch** [comment] 2022-09-08 22:36
https://user-images.githubusercontent.com/106764413/189237847-1e29b42f-7431-4a39-a721-9a2ad873633d.mp4

it's nearly unplayable

**Comment by SnabrielSnarsch** [comment] 2022-09-08 22:39
Uploading Untitled video - Made with Clipchamp (3).mp4…
it's nearly unplayable

**Comment by SnabrielSnarsch** [comment] 2022-09-08 22:39
https://user-images.githubusercontent.com/106764413/189238186-9ad1c5a4-2a33-4327-b65a-06245c3256d7.mp4

nearly unplayable

**Comment by dobacetr** [comment] 2022-09-09 09:56
Gold bags are simply broken. They need to be collected upon "collision" as it was intended.

**Comment by Whyfisher** [comment] 2022-09-09 12:49
Just wanted to bump this - it's not such a big problem on most waves to manually pick up the bags but on the "Gold" waves where you drop a lot of bags it is literally impossible to collect even half the bags that are dropping despite using shift click to queue up clicking as many bags as possible. Me and a 5 stack played this (we beat the event in it's original iteration) and we gave up after a few attempts - near impossible in it's current state.

**Comment by TheUnholyWrath** [comment] 2023-04-19 01:16
You can close this issue.

**Closed** 2023-04-19 03:13 UTC
