### ISSUE TITLE
Taunts unequipping themselves

### ISSUE THREAD

**Issue by deltakopta** [ValveSoftware/Dota2-Gameplay#19378] opened 2024-06-13 19:16 UTC
### Description

Owned taunts are sometimes unequipped seemingly randomly. Some were after some recent patches, some even between patches/games. Just unequipped for no reason.

**Comment by BgueC6595** [comment] 2024-06-17 13:02
duplicate of #18703

**Comment by chrisf-valve** [comment] 2024-06-18 15:54
This should be fixed in an update that shipped yesterday night.

**Closed by chrisf-valve** 2024-06-18 15:54 UTC
