### ISSUE TITLE
Taunts are unequipping on their own. 

### ISSUE THREAD

**Issue by MrCrunchy** [ValveSoftware/Dota2-Gameplay#18703] opened 2024-05-25 15:39 UTC
### Cosmetic Item Name

Taunts

### Description

Taunts are automatically unequipping. 

If I go to the hero in the Heroes tab the taunt doesn't always show. I have to manually go to customize and equip the taunt, then the slot shows. I hit save but then if I go to a different hero the taunt gets unequipped.

### Example Match ID

7753033572

**Comment by PowaHouse** [comment] 2024-06-02 06:17
Also, for heroes that have a persona, it gets deselected constantly as well, and you have to manually set it every game and every time you open the hero in the heroes tab.

**Comment by vcv8** [comment] 2024-06-04 15:34
From the heros tab when you have a hero selected that doesn't have a taunt equipped and jump to a hero with an equipped taunt it will automatically unequip itself.

**Comment by RedVampirium** [comment] 2024-06-06 20:57
same here keeps equipping by it self
my Steam ID: 76561199319275076

**Comment by Kyleoth** [comment] 2024-06-17 13:04
Same here, it's getting tiring

**Comment by Strugglemeat** [comment] 2024-06-17 14:38
same

**Comment by chrisf-valve** [comment] 2024-06-18 15:54
This should be fixed in an update that shipped yesterday night.

**Closed by chrisf-valve** 2024-06-18 15:54 UTC

**Comment by LokeLok** [comment] 2024-06-18 17:26
@chrisf-valve I just tested this and the taunts are instantly unequipped atm. I'm not sure if you're referring to a server update only or not, because there was no update to the client yesterday. The issue is not resolved.

**Comment by chrisf-valve** [comment] 2024-06-18 17:45
Ah you are right, sorry. Looks like the update hasn't shipped yet, but should today. Thank you for your patience.

**Comment by LokeLok** [comment] 2024-06-18 17:51
Thank you for the clarification!
