### ISSUE TITLE
Silencer - last word - bug

### ISSUE THREAD

**Issue by Under-Mod** [ValveSoftware/Dota2-Gameplay#3003] opened 2022-09-10 20:54 UTC
### Ability name

last word 

### Description

When using Last Word on Enigma/Shadow Shaman/Warlock/Base etc - these heroes can use channeling spells and not get silence while they use the ability. If Upheaval is applied for 9 seconds, Warlock will receive Silence only after 9 seconds.

Viedo → https://youtu.be/s3yvNXjfayM

### Example Match ID (and possibly Timestamp)

6749751806

**Comment by yckmm** [comment] 2022-09-10 20:56
Not a bug, read the alt tooltip.

**Comment by TheUnholyWrath** [comment] 2023-04-19 01:29
You can close this issue.

**Closed** 2023-04-19 07:10 UTC
