### ISSUE TITLE
Earth Spirit kick bug

### ISSUE THREAD

**Issue by AlirezaCrash** [ValveSoftware/Dota2-Gameplay#535] opened 2022-06-04 08:48 UTC
### Ability name

Boulder Smash

### Description

Earth Spirit can't kick any unit (creeps or heroes) when he has a stone in specific spots in front of Dire's tier 1 tower area. Two of the spots are shown in the images below but I'm sure there are more spots in this area. Any time you try to use Boulder Smash on any unit while you have a stone in these spots Earth Spirit walks up to the unit and attacks it instead of kicking the unit.
![171680301-80baaa1e-673f-4fc8-a794-60b3775bd4e4](https://user-images.githubusercontent.com/106863505/171991336-6a86ab12-36d5-4629-a798-d6cb7b019f02.png)
![171680081-ef3314c1-474c-49a6-8a4e-b0b02e5a13dd](https://user-images.githubusercontent.com/106863505/171991346-d9fbebf3-828a-45a4-b088-e0342e774565.png)

https://user-images.githubusercontent.com/106863505/172003426-3bfe1221-9459-4b08-bc88-6429c06e3597.mp4

### Example Match ID (and possibly Timestamp)

N/A

**Comment by LokeLok** [comment] 2022-06-04 11:38
#79 Seems to be the same as this bug report. I did a little consulting with my friend that plays Earth Spirit. I didn't realize there was a bug like this. Here's a video of the bug: https://streamable.com/g3h1o1
As long as there is a stone in this place, you can't kick anyone on the map. 

Side note: I still think kicking heroes and units should've higher priority than the stone. Not sure if it's intended or a bug tho.

**Comment by Memoframe** [comment] 2022-06-04 13:46
> #79 Seems to be the same as this bug report. I did a little consulting with my friend that plays Earth Spirit. I didn't realize there was a bug like this. Here's a video of the bug: https://streamable.com/g3h1o1 As long as there is a stone in this place, you can't kick anyone on the map.
> 
> Side note: I still think kicking heroes and units should've higher priority than the stone. Not sure if it's intended or a bug tho.

It depends on targeting and distance to a stone. If area is targeted then stone in 200 units radius will be smashed. To smash hero you should smash directly a hero but tbh I never can do it, I'm not so precise. Also according to wiki there should not be a stone between ES and targeted hero when you smash him.

**Comment by LokeLok** [comment] 2022-06-04 23:58
> Also according to wiki there should not be a stone between ES and targeted hero when you smash him.

This is the thing though. Is this an intended mechanic or just a side-effect, based on the changes they made back in 6.82?(most likely the time behavior change. Before this, heroes and units had priority over stone). If it has been a side-effect(a bad side-effect, with only downsides) all along, we can call it a bug and it should be fixed. Now, if this is intended behavior from the game play devs, then we can just discard my points and move on. Im not here to argue about gameplay balance, im just checking if something has been overlooked, when changing something in the past. I would like to add, that there are many Earth Spirit players out there, being very annoyed with this behavior. It is also a bit weird, that kicking and pulling the stone has two different behaviors.

**Comment by BlueHammer** [comment] 2022-06-05 10:51
Thank you so much for this ticket. This bug has been very elusive to repro for the longest time, great that someone finally figure it out. That specific spot is the 0,0,0 coordinate of the map. Placing stone in 0,0,0 in demo map will likewise disable the kicking unit ability of Q.

Hopefully this captures all the cases of 'unable to kick with Q'.

Anyway, have updated the Earth Spirit megathread bug in issue #336 , please do upvote it.

**Comment by LokeLok** [comment] 2022-09-01 08:17
This bug was fixed in the 7.32 patch

**Closed** 2024-12-27 17:11 UTC
