### ISSUE TITLE
dust is doing damage to smoked targets

### ISSUE THREAD

**Issue by bradleydragon** [ValveSoftware/Dota2-Gameplay#12398] opened 2023-10-01 13:21 UTC
### Item name

smoke and dust

### Description

was playing as axe and while smoked i tried to blink call into a teamfight, a dust was used. getting within sight of the fight the 15 dmg put my blink on cd. so i wasted my q standing still.

### Example Match ID and Timestamp

7359585509 - 37:20

**Comment by bradleydragon** [comment] 2023-10-02 01:11
yet it doesn't reveal, why should it damage? same for slark ult/shard

**Comment by commentator24** [comment] 2023-10-02 03:22
please close this issue, it's not a bug. 
read dust and smoke tooltip..
smoke turn players invisible
dust, when revealing invisible units deal 25 dmg...
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/109324155/0fb82fcf-9da3-41c3-9bca-aa877a75dfca)

**Closed** 2023-10-02 03:27 UTC
