### ISSUE TITLE
VAC Warning Suddenly Jumps Out During FIND MATCH

### ISSUE THREAD

**Issue by Crystal-N0va-lce** [ValveSoftware/Dota2-Gameplay#5775] opened 2022-12-02 14:41 UTC
### Description

This VAC warning happened twice to me although I did nothing that breached the rules with my machine. The first time it happened was on 9th November 2022, and the second time when it jumped out again with the game match ready was on 30th November 2022. When the warning was displaying on the screen, I can't do anything instead of just accepting my game match because the match has been found but the VAC warning message suddenly jumps out. Have you guys ever meet the same situation as me before? 

FYI, I have been sending tickets to Steam Support two times. The first ticket was quickly responded to when the team suggested I go for some procedures with "clean booting" of the PC or contact Microsoft Support to speak for any inquiries. However, to me, the suggestions don't seem good because it's not a good idea to find out the cause of the issue there where a machine has to run with good security monitoring in order to prevent any hackers from breaching with the aim of data-steal or ransomware attack. In addition, Steam and Dota 2 are two applications that require good graphic support such as NVIDIA processing in order for the best game performance. Therefore, the suggestions are not the best to go.

When it happened for the second time, my ticket was quickly responded to. I appreciate the quick response there. But they suggested I to go either the "Official Dota 2 Community Hub" or "Dota 2 Development Forums" where I can say the community hub of the Dota 2 is not a good place to be visited for discussion of this issue. Therefore, I came here to seek a resolution to this issue. Again to ask, does anyone face or experience such a situation like me before? 

Next question is, will it be dangerous if our Dota 2 account or game suddenly receives a VAC ban for no reason? 

### Screenshots

![Dota 2 Screenshot 2022 11 09 - 23 50 06 92](https://user-images.githubusercontent.com/117380364/205312122-b1a95e98-383e-49b8-8d31-e3ff8a885008.png) - NOTE: white areas for censoring purpose only

**Comment by sadaharu25** [comment] 2022-12-02 18:04
Try verifying your game files first

**Comment by commentator24** [comment] 2022-12-02 18:28
happened to me in April. I think I was playing Lost Ark while queuing. I canceled game found, restarted dota 2. message still appear.

Then I verify game files. i think 6 were corrupted? my SSD is a bit old. I think message appears because some files missing / corrupted / does not match. After verify, the message still appears. 

so i clicked steam setting and clear download cache. change download region, find my steam clientregistry.blob file and deleted it. Then verify again. i think 1 file replaced? Then i defrag optimize drive, and disk cleanup both my C drive and other drive where I installed steam. Restarted my PC. Works fine after that so i change back my download region on steam setting.

**Comment by Crystal-N0va-lce** [comment] 2022-12-03 03:42
> Try verifying your game files first

The game files have been verified. The local files are all validated. You cannot expect a Steam users to keep verifying their local files, right? Once per day? Means 30 times verification per month? That's extreme already if so. Quite a joke if running something in extreme way.

**Comment by Crystal-N0va-lce** [comment] 2022-12-03 03:44
> happened to me in April. I think I was playing Lost Ark while queuing. I canceled game found, restarted dota 2. message still appear.
> 
> Then I verify game files. i think 6 were corrupted? my SSD is a bit old. I think message appears because some files missing / corrupted / does not match. After verify, the message still appears.
> 
> so i clicked steam setting and clear download cache. change download region, find my steam clientregistry.blob file and deleted it. Then verify again. i think 1 file replaced? Then i defrag optimize drive, and disk cleanup both my C drive and other drive where I installed steam. Restarted my PC. Works fine after that so i change back my download region on steam setting.

Can it be due to the old junk files that came from the download cache? What is clientregistry.blob file as you meant there? I never touch my folder files before.

**Comment by commentator24** [comment] 2022-12-04 15:05
i was going to screenshot my blob file, it's simply where you installed steam, but i cant find it anymore. a bit of googling says they dont use blob file anymore, but you still can flushconfig. as i've said my PC is old hehe sorry. 
![image](https://user-images.githubusercontent.com/109324155/205498287-bfe3ba9e-6547-4059-81be-74458818817b.png)

Try go to your steam setting and change download region and clear download cache first

**Comment by Crystal-N0va-lce** [comment] 2022-12-05 01:24
> i was going to screenshot my blob file, it's simply where you installed steam, but i cant find it anymore. a bit of googling says they dont use blob file anymore, but you still can flushconfig. as i've said my PC is old hehe sorry. ![image](https://user-images.githubusercontent.com/109324155/205498287-bfe3ba9e-6547-4059-81be-74458818817b.png)
> 
> Try go to your steam setting and change download region and clear download cache first

That is a way to "reset" (flushing away) all the configurations of the Steam platform? I don't feel it's good in detecting the cause of the sudden appearing message by VAC. I hope you get what I mean in between the "sudden" and "non-sudden" appearing message.

**Comment by commentator24** [comment] 2022-12-05 18:04
no i dont know what you mean by sudden and non sudden message. did you mean when you just launched dota? or first game was fine and 2nd game pops up? well it might be just basic network issues with your IP address. If VAC and Valve servers cant keep up connection to authenticate your session then try process of elimination on what's causing the problem, like verify game files, port forwarding router, check firewall, exit and restart steam etc. always start from something simple like verifying game files, disk cleanup, clear cache, clear steam download cache etc.

if files verified without errors then the problem is elsewhere you dont need to keep verifying it everyday that's just silly. in my case i had 6 errors and i know my SSD and motherboard are failing. i have old PC so data might be corrupted due to memory errors. out of memory etc because my CPU is always running at 100% to play dota. maybe it cant keep up? maybe packet loss and fails to connect to VAC secured servers? who knows. you can also try opening task manager while running dota to see if theres any issues maybe duplicate processes, out of memory etc.

so i might repeat verify when i've tried everything i know, just to make sure it's 0 errors this time after i changed download region. maybe server side has errors due to recent updates so i need to try other download region. what works for me might not work for you because you have different modem, router setting, dynamic ip address, or different modem protocol maybe? i dont know. you wont fix the problem if all you do is complaining that wont work. you might think you did nothing wrong, but not everything is because of steam. it could be your windows setting e.g. firewall, your drivers, your pc parts, your modem, your modem setting etc. but most likely your modem setting, e.g. your turned on pc and first game of dota was fine but when queuing next game you receive VAC message. well maybe because each game has different router numbers for connecting to the server, team voice chat, and steam network. so when game finished and not used anymore it will close and maybe also close VAC secured server connection after 5 min because it's idle for some reason or even prevent future connections due to modem setting, so this VAC message pops up while you queue. you could restart steam and pc everytime you finished a dota game but that's just silly right? might as well explore your firewall, IP address protocol and modem setting.

**Comment by Crystal-N0va-lce** [comment] 2022-12-05 18:32
> no i dont know what you mean by sudden and non sudden message. did you mean when you just launched dota? or first game was fine and 2nd game pops up? well it might be just basic network issues with your IP address. If VAC and Valve servers cant keep up connection to authenticate your session then try process of elimination on what's causing the problem, like verify game files, port forwarding router, check firewall, exit and restart steam etc. always start from something simple like verifying game files, disk cleanup, clear cache, clear steam download cache etc.
> 
> if files verified without errors then the problem is elsewhere you dont need to keep verifying it everyday that's just silly. in my case i had 6 errors and i know my SSD and motherboard are failing. i have old PC so data might be corrupted due to memory errors. out of memory etc because my CPU is always running at 100% to play dota. maybe it cant keep up? maybe packet loss and fails to connect to VAC secured servers? who knows. you can also try opening task manager while running dota to see if theres any issues maybe duplicate processes, out of memory etc.
> 
> so i might repeat verify when i've tried everything i know, just to make sure it's 0 errors this time after i changed download region. maybe server side has errors due to recent updates so i need to try other download region. what works for me might not work for you because you have different modem, router setting, dynamic ip address, or different modem protocol maybe? i dont know. you wont fix the problem if all you do is complaining that wont work. you might think you did nothing wrong, but not everything is because of steam. it could be your windows setting e.g. firewall, your drivers, your pc parts, your modem, your modem setting etc. but most likely your modem setting, e.g. your turned on pc and first game of dota was fine but when queuing next game you receive VAC message. well maybe because each game has different router numbers for connecting to the server, team voice chat, and steam network. so when game finished and not used anymore it will close and maybe also close VAC secured server connection after 5 min because it's idle for some reason or even prevent future connections due to modem setting, so this VAC message pops up while you queue. you could restart steam and pc everytime you finished a dota game but that's just silly right? might as well explore your firewall, IP address protocol and modem setting.

Thanks a lot for the fast and quick responses :) I think it should be the network issues because I can understand your way of explaining to me where I can understand and check my PC back to understand it was due to my personal activities/deeds behind. Good steps and advice. Appreciating a lot :) TQ again. 

Good answer. 

CLOSED.

**Closed** 2022-12-05 18:32 UTC
