### ISSUE TITLE
Failed to load rendersystemdx11.dll

### ISSUE THREAD

**Issue by serif188** [ValveSoftware/Dota2-Gameplay#2597] opened 2022-09-01 22:50 UTC
### Description

Whenever I try to launch dota 2 an error would pop up that reads "Failed to load rendersystemdx11.dll, which is the default render system and should not fail to load. Please verify the game install in Steam."
I have verified the integrity of game files multiple times and also reinstalled the game but I still get the same error.

### Screenshots

![image](https://user-images.githubusercontent.com/22858911/188025290-58d764e1-cf97-4086-9551-82c2b4571418.png)

**Comment by Nathanael-Valve** [comment] 2022-09-01 22:58
We're looking into this, thanks!

**Comment by 4ioros** [comment] 2022-09-01 23:54
did you find any solution?

**Comment by Nathanael-Valve** [comment] 2022-09-01 23:55
The next update has some fixes, yes. They fix some of these issues and hopefully this one too (this one in particular has been harder to repro).

**Comment by OwenKolento** [comment] 2022-09-02 00:02
Same problem here, I tried to reinstall and verify game files integrity, but none of them worked

**Comment by 4ioros** [comment] 2022-09-02 00:06
I still try the same as you and try to find other solutions and nothing to solve it.

**Comment by josep0121** [comment] 2022-09-02 00:13
same problem any solution ?

**Comment by Saguaro92** [comment] 2022-09-02 00:35
I'm also experiencing this issue. Tried reinstalling, verifying game files, and running the exe as an admin but still no dice.

**Comment by calaquend1** [comment] 2022-09-02 00:40
for me "borderless window" option worked and fixed the problem
+ I only could launch the game properly from here "C:\Steam\steamapps\common\dota 2 beta\game\bin\win64" starting dota2.exe

**Comment by akson33mini** [comment] 2022-09-02 01:24
> 

how you setup a borderless out of application?

**Comment by darkzekk** [comment] 2022-09-02 01:28
I tried launching from here "C:\Steam\steamapps\common\dota 2 beta\game\bin\win64" but it does the same thing and instantly throws up the error message

**Comment by OwenKolento** [comment] 2022-09-02 01:38
Quote from reddit:https://www.reddit.com/r/DotA2/comments/w4w7x5/comment/imqj1fz/?utm_source=share&utm_medium=web2x&context=3

https://www.microsoft.com/en-us/download/details.aspx?id=52685
Everyone try to install this, worked for me.

**Comment by darkzekk** [comment] 2022-09-02 01:40
Worked for me too!!

**Comment by serif188** [comment] 2022-09-02 01:45
Downloading this Microsoft Visual C++ 2015 Redistributable seems to have fixed the problem

**Comment by dhruvmongia** [comment] 2022-09-02 01:49
Downloading Microsoft Visual C++ 2015 Redistributable works for me as well. Thanks <3

**Comment by akson33mini** [comment] 2022-09-02 02:35
> Downloading Microsoft Visual C++ 2015 Redistributable works for me as well. Thanks <3

Working for me, thanks!

**Comment by akson33mini** [comment] 2022-09-02 02:37
Valve launched att for distribute this packet

**Comment by Nathanael-Valve** [comment] 2022-09-02 03:31
Should be fixed now.

**Closed by Nathanael-Valve** 2022-09-02 03:31 UTC

**Comment by Nasirdota** [comment] 2022-09-02 13:42
Not working for me :(

**Comment by wangtao0101** [comment] 2022-09-02 13:57
@Nasirdota  This doesn't work for me, should reopen

**Comment by Triplek7** [comment] 2022-09-02 14:11
> Debería arreglarse ahora.

Not working for me

**Comment by disaled21** [comment] 2022-09-02 14:32
@Nathanael-Valve game still not launching, pls open issue.

**Comment by omarbot06** [comment] 2022-09-02 18:09
the error continues, now steam tries to download Microsoft Visual C++ 2015 but the error appears again

**Comment by Xaima0** [comment] 2022-09-02 18:27
I also can’t enter DotA, the error comes out fix the error

**Comment by wasabisama** [comment] 2022-09-02 18:45
same problem still cant log in

**Comment by errordota** [comment] 2022-09-02 18:52
the error continues, now steam tries to download Microsoft Visual C++ 2015 but the error appears again

**Comment by LethalDMG** [comment] 2022-09-02 19:48
Still having this error.  I have 1060 6GB card if that might be helpful.

**Comment by Nathanael-Valve** [comment] 2022-09-03 01:19
We found and fixed another one of these errors. Deploying it now.

**Comment by Osas976** [comment] 2022-09-03 05:38
downloaded and installed Microsoft Visual C++ 2015 but the error appears again

**Comment by McLovin08** [comment] 2022-09-03 07:08
failed to load render i try everything help!!!

**Comment by McLovin08** [comment] 2022-09-03 07:21
![image](https://user-images.githubusercontent.com/112748776/188260491-a659eda9-bfcb-4ae1-b0b8-023dea032610.png)

**Comment by LethalDMG** [comment] 2022-09-03 07:32
Still having the same issue

**Comment by wasabisama** [comment] 2022-09-03 07:34
there was an update right now but that didnt fix its still the same the error :((

**Comment by omarbot06** [comment] 2022-09-03 08:08
solve the problem using windows update, checking for system updates, the process can be slow but after you install updates you must uninstall all the Microsoft visuals that you have installed (from the control panel) and reload and install visual c++ 2015 corresponds to your 32 or 64 bit Windows

**Comment by coma2121** [comment] 2022-09-03 08:35
Got the same problem. Can't play for 2 days after the updates with BP. I did all reinstall visual C++. reinstall dota, reinstall steam, verifying game files. Then Open Steam.
Go to the "Library"
Right-click the game which needs to be reconfigured.
Select "Properties" from the menu.
Go to the "Launch Options" section in the window.
Remove any launch options currently shown.
Type. -autoconfig. in the box and close the window.
Launch the game and test the issue again.

Still not working, pls help this are my days off. I want to spent my money on the BP. LORD GABEN HELP ME !

**Comment by LethalDMG** [comment] 2022-09-03 09:36
> solve the problem using windows update, checking for system updates, the process can be slow but after you install updates you must uninstall all the Microsoft visuals that you have installed (from the control panel) and reload and install visual c++ 2015 corresponds to your 32 or 64 bit Windows

This worked for me thanks, although when it came to uninstalling the current Microsoft visuals, they gave the option to repair which i used and that fixed it.

**Comment by Aboberss22** [comment] 2022-09-03 13:56
ok thanks Valve 
![image](https://user-images.githubusercontent.com/112765646/188273703-73ffd7e5-316d-432e-ae55-e01d2d58a36b.png)

**Comment by newaurum** [comment] 2022-09-03 17:32
when will valve fix this garbage 2 days waiting

**Comment by newaurum** [comment] 2022-09-03 17:33
they just need to disable the fucking install script microsoft visual

**Comment by DavidTaira** [comment] 2022-09-03 20:04
@Nathanael-Valve  I've been waiting for 2 days for them to fix this problem so I can play and I can't get in so far, please do something, I'm asking you, still getting the same error rendersystemdx11.dll

**Comment by guitar525** [comment] 2022-09-04 00:33
PLEASE @Nathanael-Valve WE THE DOTA 2 COMMUNITY ARE BEGGING

**Comment by PyaeSone398** [comment] 2022-09-04 04:30
@Nathanael-Valve 
1. I already type -dx -safe_mode -windowed -gl everything people said that could solve the error.
2.  I also install the Microsoft C++ 2015.
3. I even uninstall and reinstall Dota 2.4
4. Alsoe tried "Veryfing game files.
Non of it doesn't work.
I also restart my computer a few time after changed setting.

**Comment by wasabisama** [comment] 2022-09-04 07:39
at this point i'll just cry, fix the problem pleaseeeeeeeeeeeeeeeee @Nathanael-Valve

**Comment by Nasirdota** [comment] 2022-09-04 08:26
I install my window again and it's working

**Comment by Nasirdota** [comment] 2022-09-04 08:27
Reinstall your windows and then dota2 it's works for me

**Comment by newaurum** [comment] 2022-09-04 08:36
> Reinstall your windows and then dota2 it's works for me


that is, because of the valve, people should reinstall Windows, let them disable the fucking script that installs Microsoft Visual

**Comment by jasper929** [comment] 2022-09-04 13:40
now this method fix this for me just uninstall al VS C++ on control panel then install this https://www.microsoft.com/en-us/download/details.aspx?id=52685

**Comment by newaurum** [comment] 2022-09-04 16:24
> now this method fix this for me just uninstall al VS C++ on control panel then install this https://www.microsoft.com/en-us/download/details.aspx?id=52685

dont work for me=)

**Comment by newaurum** [comment] 2022-09-04 16:25
> now this method fix this for me just uninstall al VS C++ on control panel then install this https://www.microsoft.com/en-us/download/details.aspx?id=52685

i cant even visual c++ download error)

**Comment by RizkiAdlani** [comment] 2022-09-04 17:10
> ### Description
> 
> Whenever I try to launch dota 2 an error would pop up that reads "Failed to load rendersystemdx11.dll, which is the default render system and should not fail to load. Please verify the game install in Steam." I have verified the integrity of game files multiple times and also reinstalled the game but I still get the same error.
> ### Example Match ID (and possibly Timestamp)
> 
> _No response_
> ### Screenshots
> 
> ![image](https://user-images.githubusercontent.com/22858911/188025290-58d764e1-cf97-4086-9551-82c2b4571418.png)

if you experience rendering error, follow my instructions
1. Download microsoft update windows 7 SP 1 32/64 bit > link https://www.techpowerup.com/download/microsoft-windows-7-service-pack-1/ and install
2. If you have finished it, download update again, link > https://www.microsoft.com/en-us/download/details.aspx?id=36805
3. Install file update
4. Waiting install and restart your PC
5. Open Steam and play Dota 2

**Comment by RizkiAdlani** [comment] 2022-09-04 17:15
if you experience rendering error, follow my instructions

1. Download microsoft update windows 7 SP 1 32/64 bit > link https://www.techpowerup.com/download/microsoft-windows-7-service-pack-1/ and install
2. If you have finished it, download update again, link > https://www.microsoft.com/en-us/download/details.aspx?id=36805
3. Install file update
4. Waiting install and restart your PC
5. Open Steam and play Dota 2

**Comment by newaurum** [comment] 2022-09-04 18:47
> if you experience rendering error, follow my instructions
> 
> 1. Download microsoft update windows 7 SP 1 32/64 bit > link https://www.techpowerup.com/download/microsoft-windows-7-service-pack-1/ and install
> 2. If you have finished it, download update again, link > https://www.microsoft.com/en-us/download/details.aspx?id=36805
> 3. Install file update
> 4. Waiting install and restart your PC
> 5. Open Steam and play Dota 2

dont work for me(

**Comment by iwangjintian** [comment] 2022-09-05 04:27
How come this issue is closed? Bunch of people still have this problem. Do we have a root cause? Is there a mitigation step?

**Comment by AdeleZONE** [comment] 2022-09-05 06:43
@Nathanael-Valve hello? can u fix it somehow?

**Comment by iambigslon** [comment] 2022-09-05 08:37
Still not working. 
Windows 7 64 bit / Nvidia 1050ti
Already try everything from above.
Please fix it!!!
It's rare to update windows or c++ after each BP!!!

**Comment by Alirezadsh** [comment] 2022-09-05 08:52
i had the same issue since the last patch...pls fix the game. i also tried everthing from above.

**Comment by Alirezadsh** [comment] 2022-09-05 08:54
Still waiting for Valve to fix this issue...
Already try everything from above but still not working

**Comment by RizkiAdlani** [comment] 2022-09-05 11:32
> > if you experience rendering error, follow my instructions
> > 
> > 1. Download microsoft update windows 7 SP 1 32/64 bit > link https://www.techpowerup.com/download/microsoft-windows-7-service-pack-1/ and install
> > 2. If you have finished it, download update again, link > https://www.microsoft.com/en-us/download/details.aspx?id=36805
> > 3. Install file update
> > 4. Waiting install and restart your PC
> > 5. Open Steam and play Dota 2
> 
> dont work for me(

windows 7 ultimate ?

**Comment by Aboberss22** [comment] 2022-09-05 19:02
we have to wait until they fix it or just ignore us:)

**Comment by AdeleZONE** [comment] 2022-09-05 19:36
> we have to wait until they fix it or just ignore us:)

seems like that

**Comment by ekie-airey** [comment] 2022-09-06 07:17
i think they fix it now with the new update..

**Comment by AdeleZONE** [comment] 2022-09-06 07:25
> ekie

yea

**Comment by AdeleZONE** [comment] 2022-09-06 07:25
yup

**Comment by berkaybaran12** [comment] 2022-09-06 10:28
> > > oluşturma hatasıyla karşılaşırsanız talimatlarımı izleyin
> > > 
> > > 1. Microsoft güncelleme windows 7 SP 1 32/64 bit'i indirin > https://www.techpowerup.com/download/microsoft-windows-7-service-pack-1/ bağlantısını kurun ve yükleyin
> > > 2. Bitirdiyseniz, güncellemeyi tekrar indirin, bağlantı > https://www.microsoft.com/en-us/download/details.aspx?id=36805
> > > 3. Dosya güncellemesini yükle
> > > 4. Yüklemeyi ve PC'nizi yeniden başlatmayı bekliyor
> > > 5. Steam'i açın ve Dota 2 oynayın
> > 
> > 
> > benim için çalışma (



my pc win 7 ultimate error persists densini my problem is solved

**Comment by newaurum** [comment] 2022-10-11 07:42
Yeah

пн, 5 сент. 2022 г., 14:32 RizkiAdlani ***@***.***>:

**Comment by plugcrypt** [comment] 2022-11-30 20:58
Didnt played dota for long too, opening the dota.exe file in the game directory was a success

**Comment by barbaduk** [comment] 2022-12-03 20:08
I'm getting the same error.
It started after windows update. 
Reinstalled every MV C++ and video drivers, waited for dota update twice - nothing helps. 
Launching exe from dota's folder works, but that's lame.

Is there a fix? Or maybe specific microsoft KB* update that i need to un/re-install?

**Comment by johan-stenqvist** [comment] 2022-12-04 09:56
This exact error happens to me now as well. Reinstalling MV C++ did not help.
I cannot say this was after a windows update or a dota update. 

I am also able to start the game from the exe file in the dota folder.

Any suggestion in getting this resolved would be much appreciated!

**Comment by manofmans** [comment] 2022-12-06 11:21
у меня виндоус 10 ошибка та же нечего не помгает пробавал все что вожможно корме пере установки виндоуса помогите был бы блогадарен

**Comment by asknask** [comment] 2023-09-27 22:56
This has been closed but it happened to me just now after the compendium update. I've up-to-date Visual C++ stuff. Still got the error. Verifying integrity didn't help either.

CMaterialSystem32AppSystemDict::AddRenderSystem():

**Comment by FalkHogan** [comment] 2023-09-27 23:42
> This has been closed but it happened to me just now after the compendium update. I've up-to-date Visual C++ stuff. Still got the error. Verifying integrity didn't help either.
> 
> CMaterialSystem32AppSystemDict::AddRenderSystem():

Same, brother. Same. Tried a random video (turning on / off Hardware acceleration + WinUpdate) already, VisualC++ is up2date also. Needless to say, verifying does not do the job.

**Comment by asknask** [comment] 2023-09-27 23:45
> > This has been closed but it happened to me just now after the compendium update. I've up-to-date Visual C++ stuff. Still got the error. Verifying integrity didn't help either.
> > CMaterialSystem32AppSystemDict::AddRenderSystem():
> 
> Same, brother. Same. Tried a random video (turning on / off Hardware acceleration + WinUpdate) already, VisualC++ is up2date also. Needless to say, verifying does not do the job.

Oh I figured out why it was causing issues for me. Do you use reshade/sweetfx by any chance? If so, remove it. It is currently causing issues with dota for some reason.

**Comment by FalkHogan** [comment] 2023-09-27 23:45
> > > This has been closed but it happened to me just now after the compendium update. I've up-to-date Visual C++ stuff. Still got the error. Verifying integrity didn't help either.
> > > CMaterialSystem32AppSystemDict::AddRenderSystem():
> > 
> > 
> > Same, brother. Same. Tried a random video (turning on / off Hardware acceleration + WinUpdate) already, VisualC++ is up2date also. Needless to say, verifying does not do the job.
> 
> Oh I figured out why it was causing issues for me. Do you use reshade/sweetfx by any chance? If so, remove it. It is currently causing issues with dota for some reason.

I actually do, hahaha, sec

**Comment by asknask** [comment] 2023-09-27 23:46
> > > > This has been closed but it happened to me just now after the compendium update. I've up-to-date Visual C++ stuff. Still got the error. Verifying integrity didn't help either.
> > > > CMaterialSystem32AppSystemDict::AddRenderSystem():
> > > 
> > > 
> > > Same, brother. Same. Tried a random video (turning on / off Hardware acceleration + WinUpdate) already, VisualC++ is up2date also. Needless to say, verifying does not do the job.
> > 
> > 
> > Oh I figured out why it was causing issues for me. Do you use reshade/sweetfx by any chance? If so, remove it. It is currently causing issues with dota for some reason.
> 
> I actually do, hahaha, sec

Just remove or rename dxgi.dll to something else (add .bak). Run the game and enjoy.

**Comment by FalkHogan** [comment] 2023-09-27 23:48
> > > > > This has been closed but it happened to me just now after the compendium update. I've up-to-date Visual C++ stuff. Still got the error. Verifying integrity didn't help either.
> > > > > CMaterialSystem32AppSystemDict::AddRenderSystem():
> > > > 
> > > > 
> > > > Same, brother. Same. Tried a random video (turning on / off Hardware acceleration + WinUpdate) already, VisualC++ is up2date also. Needless to say, verifying does not do the job.
> > > 
> > > 
> > > Oh I figured out why it was causing issues for me. Do you use reshade/sweetfx by any chance? If so, remove it. It is currently causing issues with dota for some reason.
> > 
> > 
> > I actually do, hahaha, sec
> 
> Just remove or rename dxgi.dll to something else (add .bak). Run the game and enjoy.

Works like a charm. My man, ty alot!

**Comment by asknask** [comment] 2023-09-27 23:49
> > > > > > This has been closed but it happened to me just now after the compendium update. I've up-to-date Visual C++ stuff. Still got the error. Verifying integrity didn't help either.
> > > > > > CMaterialSystem32AppSystemDict::AddRenderSystem():
> > > > > 
> > > > > 
> > > > > Same, brother. Same. Tried a random video (turning on / off Hardware acceleration + WinUpdate) already, VisualC++ is up2date also. Needless to say, verifying does not do the job.
> > > > 
> > > > 
> > > > Oh I figured out why it was causing issues for me. Do you use reshade/sweetfx by any chance? If so, remove it. It is currently causing issues with dota for some reason.
> > > 
> > > 
> > > I actually do, hahaha, sec
> > 
> > 
> > Just remove or rename dxgi.dll to something else (add .bak). Run the game and enjoy.
> 
> Works like a charm. My man, ty alot!

I hope I can find a workaround though. Love the contrasty look dota gives with it.

**Comment by kingsoul979** [comment] 2023-12-15 06:41
I just get into the profile of cs2 and find cs2.exe, then set to open it as admin, and solve it

**Comment by ymj4023** [comment] 2024-08-25 14:11
Whenever I try to launch dota 2 an error would pop up that read:failed to load rendersystemdx11.dll,which is the default rendersystem and should not fail to load.Please verify the game install in Steam

**Comment by janst44** [comment] 2024-08-26 02:42
same

**Comment by specurial** [comment] 2025-07-07 19:37
same again (after 1year same issue is back) gaben what are u doing with some of us? :)
