### ISSUE TITLE
Drows lvl 10 gust movement speed talent.

### ISSUE THREAD

**Issue by EHK-Duke** [ValveSoftware/Dota2-Gameplay#6214] opened 2022-12-26 13:00 UTC
### Ability name

Gust - lvl 10 talent

### Description

The tooltip says it grants Drow +15% self movement speed.
The talent actually gives her 25% movement speed.

I tested it in Demo without any items that give move speed. 
So she had 300 move speed. Cast gust, now she has 375, which is +25% move speed.
Talent states +15% which should have left her at 345.
The buff she gets when she casts gust while having this talent actually states +25% move speed.
The Talent tooltip however states +15%

### Example Match ID (and possibly Timestamp)

This is easily testable in Demo, i dont have a match to link.

**Comment by shaileshgarg** [comment] 2022-12-26 14:09
Gust without the talent has 10% movement speed bonus, and with the Talent 15%, in total it becomes 25%, so it is working as intended.

**Comment by EHK-Duke** [comment] 2022-12-26 15:12
My bad :D
Thanks for clearing that up for me

**Comment by shaileshgarg** [comment] 2023-01-05 03:22
You can close the issue

**Closed** 2023-01-05 14:45 UTC
