### ISSUE TITLE
Hoodwink Bushwhack highlight not working as intented. Hero demo shows ability working as intented. Within matches the ability does not work as intended.

### ISSUE THREAD

**Issue by Gigarange** [ValveSoftware/Dota2-Gameplay#7435] opened 2023-03-10 06:23 UTC
Dota2 Version: 5,640
Gameplay Version: 7.32E

Bushwack working as intended within hero demo:

https://user-images.githubusercontent.com/90445697/224238915-b62520d5-4d66-4f43-8202-7cb324ec46f1.mp4

Bushwack not working as intended within matches:

https://user-images.githubusercontent.com/90445697/224664847-567e7e2f-3485-4b7c-b2a6-b7c0bbaec5ec.mp4

Dota2 Version: 5,645
Gameplay Version: 7.32E

Bushwack mechanic working custom game:

https://user-images.githubusercontent.com/90445697/224661867-a3be8443-8766-4197-a648-0f61feeab01c.mp4

**Comment by Gigarange** [comment] 2023-03-14 10:52
As of Version: 5,645 the mechanic seems to be working outside of hero demo. But Highlight still not working.

**Comment by eugene-valve** [comment] 2023-10-25 23:52
Closing as a duplicate of #399

**Closed by eugene-valve** 2023-10-25 23:52 UTC

**Comment by zanthous** [comment] 2024-02-20 14:49
> Closing as a duplicate of #399

Not a duplicate, the highlighting doesn't work on many terrains. The issue you linked is a different issue
