### ISSUE TITLE
Rubick Telekinesis on Legion Commander going on cooldown but without effect

### ISSUE THREAD

**Issue by Bra7wurs7** [ValveSoftware/Dota2-Gameplay#7838] opened 2023-04-03 21:29 UTC
### Ability name

Telekinesis

### Description

Last match (7091160746) I played as Rubick I cast Q on legion commander several times throughout the match and every now  and then the ability went on Cooldown without any effect at all (for example 18:00 and 30:05). I targeted LC directly.

### Example Match ID (and possibly Timestamp)

7091160746 18:00 and 30:05

**Comment by TheUnholyWrath** [comment] 2023-04-03 21:53
Duplicate of #190

**Comment by tvdisplayman** [comment] 2023-04-05 08:46
A simple, yes i know thats a mechanic would be nice :)

**Comment by TheZett** [comment] 2023-04-06 00:33
Duel causes both duel participants to become immune to certain mobility spells.

Rubick's Telekinesis is one of these spells, which is why you cannot stun LC during a duel with Rubick lift.

**Comment by Duongtran777** [comment] 2023-07-28 05:55
> Duel causes both duel participants to become immune to certain mobility spells.
> 
> Rubick's Telekinesis is one of these spells, which is why you cannot stun LC during a duel with Rubick lift.
> 
> This is not a bug, it is certainly intended, as those spells have to be manually added to Duel's exception list by the devs.

So why Tinker Shard can use on LC dueling????
Warp flare is also mobility spell????

**Comment by cwogithub** [comment] 2024-01-30 15:09
This used to work differently though.
Units not permitted to be moved used to get stunned instead IIRC.
However
Paying the cost for the spell (mana and cooldown) without any effect whatsoever can not be intended behavior.
Making telekinesis not castable seems way more reasonable (and understandable for new players).

**Closed** 2024-02-03 00:38 UTC
