### ISSUE TITLE
Unexpected ability interaction between Axe's Berserker's Call and CM Ult with shard

### ISSUE THREAD

**Issue by diegoholder** [ValveSoftware/Dota2-Gameplay#8585] opened 2023-04-25 04:30 UTC
### Ability name

Berserker's Call and Freezing Field

### Description

Axe's "Berserker's Call" ability doesn't interrupt Crystal Maiden's "Freezing Field" when she has Aghanim's Shard. I had this happen in a ranked match so I tried it in Demo Mode and it seems to occur every time.

### Example Match ID (and possibly Timestamp)

7124246636

**Comment by TheUnholyWrath** [comment] 2023-04-25 09:06
Its best explained here https://github.com/ValveSoftware/Dota2-Gameplay/issues/1856#issuecomment-1188516594

Its not a bug. You can close this issue.

**Closed** 2023-04-25 09:41 UTC
