### ISSUE TITLE
Death ward causing instant death

### ISSUE THREAD

**Issue by kushalprajapati** [ValveSoftware/Dota2-Gameplay#3706] opened 2022-10-08 16:12 UTC
### Ability name

Death Ward

### Description

Tusk casts warlus punch to sniper and instant death. 
Game Time: 13:53 to 13:55
ID: 6796449320
Log attached hereby
![Capture](https://user-images.githubusercontent.com/6862752/194717022-21a97db0-0d1c-48ef-89dc-56d9164ee527.PNG)

### Example Match ID (and possibly Timestamp)

6796449320 - 13:53:53

**Comment by TheUnholyWrath** [comment] 2022-10-08 16:18
Duplicate of #244

**Comment by Dota-Exp** [comment] 2022-12-21 22:15
This will be fixed in the upcoming update. Thank you

**Closed by Dota-Exp** 2022-12-21 22:15 UTC
