### ISSUE TITLE
Overwatch Causes Crash

### ISSUE THREAD

**Issue by N774N** [ValveSoftware/Dota2-Gameplay#8260] opened 2023-04-21 21:45 UTC
Hello, I have never reviewed an overwatch case, but today it popped up. It downloads fine, but before I can enter the client crashes with this error message:
![image](https://user-images.githubusercontent.com/121876934/233739403-f47eb98b-9c56-45f0-b0a4-189bfea1f82d.png)

**Comment by pontuslaestadius** [comment] 2023-04-23 07:01
Duplicate of #8183 please close and upvote the existing ticket.

**Comment by Nathanael-Valve** [comment] 2023-05-22 22:59
Fixed

**Closed by Nathanael-Valve** 2023-05-22 22:59 UTC
