### ISSUE TITLE
Winter's curse mysteriously disappears before the skill duration ends

### ISSUE THREAD

**Issue by Lotto1111** [ValveSoftware/Dota2-Gameplay#5430] opened 2022-11-14 19:41 UTC
### Ability name

winter's curse

### Description

Winter's curse debuff does not stay on unit for the intended duration, cant figure out why and how it was removed, guessing it might be a bug

### Example Match ID (and possibly Timestamp)

6864458010, between 24:10 to 24:25 (focus on sniper)

**Comment by TheUnholyWrath** [comment] 2022-11-14 22:46
In the alt tooltip for Winters Curse it says: "If there are no allies within range of the Cursed enemy for 2.5 seconds the effect will end early.". This is not a bug. Please close this

**Closed** 2022-11-15 03:10 UTC
