### ISSUE TITLE
Anti-mage blink ignores talent extra range if clicked beyond max range

### ISSUE THREAD

**Issue by andreihareza** [ValveSoftware/Dota2-Gameplay#1735] opened 2022-07-09 12:36 UTC
### Ability name

Blink

### Description

When Antimage has the +250 cast range talent, with max blink, the cast range should be 1400. If clicked less than 1400 distance, the blink distance is correct. If clicked beyond 1400 range, the blink distance is back to 1150, ignoring the talent.

### Example Match ID (and possibly Timestamp)

https://imgur.com/wxomlTn

**Comment by TheUnholyWrath** [comment] 2022-07-09 17:48
This is a duplicate of #454, please add any new infomation to that issue and close this one

**Comment by TheUnholyWrath** [comment] 2023-04-17 01:35
This has been fixed, please close this issue.

**Closed** 2023-04-18 12:16 UTC
