### ISSUE TITLE
Battle hunger is not affected by enemies' status resistance

### ISSUE THREAD

**Issue by yongjinkai5f** [ValveSoftware/Dota2-Gameplay#9350] opened 2023-05-21 12:43 UTC
### Ability name

Battle hunger

### Description

Battle hunger lasts the full 12s regardless of enemies' status resistance. Bug or feature?

### Example Match ID (and possibly Timestamp)

NA

**Comment by TheUnholyWrath** [comment] 2023-05-21 13:34
Status Resistance reduces the value of the slow, the same way that Debuff amp increases it. The Debuff amp interaction was confirmed to be intended [here](https://github.com/ValveSoftware/Dota2-Gameplay/issues/5840#issuecomment-1340010768), and since they affect the same value Status Resistance reducing it must also be intended. You can close this issue.

**Closed** 2023-05-21 13:50 UTC
