### ISSUE TITLE
Game crashes when pinging the "Lit" tooltip of Watchers

### ISSUE THREAD

**Issue by findtravishere** [ValveSoftware/Dota2-Gameplay#8231] opened 2023-04-21 18:42 UTC
### Description

Crashed out of a ranked game and tested this subsequently in a lobby. 

**Error:**
CBufferString: CheckForUnsafeInputString: unsafe self pointer provided as a modification input.

**Steps to recreate:**
- Ping the "Lit" tooltip of watchers. 

**System Information**
- Macbook Pro 2019 16" (Intel)
- AMD Radeon Pro 5300M 4 GB, Intel UHD Graphics 630

### Screenshots

![image](https://user-images.githubusercontent.com/63047970/233711547-f0bfb2b8-eada-482e-9bca-c51440b97043.png)

**Comment by AlexanderArvidsson** [comment] 2023-04-21 19:55
Duplicate of #8160

**Closed** 2023-04-24 07:14 UTC
