### ISSUE TITLE
wrong networth bug

### ISSUE THREAD

**Issue by miamipalms** [ValveSoftware/Dota2-Gameplay#6839] opened 2023-02-02 21:32 UTC
### Description

dota 2 shows wrong networth on result screen of the match - FVoid had 75k networth but shows only 12k. you can see how it changes just in end of the match.

### Example Match ID (and possibly Timestamp)

6998757498 - 42:35>42:41

### Screenshots

![image](https://user-images.githubusercontent.com/108049580/216452458-2f36a4ad-6e03-49ee-9601-b205f1d74b19.png)

![image](https://user-images.githubusercontent.com/108049580/216452418-6a749ac3-8913-43a3-b3f4-0a415c659a73.png)

**Comment by yckmm** [comment] 2023-02-02 21:58
Duplicate of #214.
Please close this and upvote the existing issue. Also use the search before opening new issues.

**Closed** 2023-02-02 21:59 UTC
