### ISSUE TITLE
Enter a short summary here!

### ISSUE THREAD

**Issue by mludolf** [ValveSoftware/Dota2-Gameplay#2178] opened 2022-08-20 22:55 UTC
### Ability name

IO ultimate failed while linked

### Description

I was teleporting linked with my core Drow Ranger and was going, I believe, alone mostly of the times.

One of my theories is that whenever he/she used Manta, the spell would break and result in a fail Ultimate.

Someone had any similar problem in the past?

Example:

39:17 - Linked
![image](https://user-images.githubusercontent.com/78050835/185768657-944e59b7-f7da-4ce8-afa5-d259e508e9c9.png)

39:18 - TPed Alone
![image](https://user-images.githubusercontent.com/78050835/185768671-e9dfcdc5-b8d1-42ea-9029-3c5bc1517e9f.png)

39:18 - Ultimate selected respawn place
![image](https://user-images.githubusercontent.com/78050835/185768690-2101f19f-8f89-43ad-8f62-fcede103c942.png)

### Example Match ID (and possibly Timestamp)

6716747328

**Comment by TheUnholyWrath** [comment] 2022-08-21 11:38
Drow disabled help. This is not a bug. Please close this

**Comment by mludolf** [comment] 2022-08-22 01:18
> Drow disabled help. This is not a bug. Please close this

I though so, but later on the game the ult worked perfectly. I tested on the base to make sure it was working, near the place where the barracks once stood.

I don't know how to see the datalog, but is not very likely that a player keeps disabling and enabling functions during the game. If that were the case, then problem solved.

**Comment by TheUnholyWrath** [comment] 2022-08-22 02:23
If you look at player perspective, at 56:37 you can see her turn it back on

**Comment by mludolf** [comment] 2022-08-22 02:47
> If you look at player perspective, at 56:37 you can see her turn it back on

Case closed then. Thanks for your assist ;)

**Closed** 2022-08-22 02:46 UTC
